-- qwer · 2026-10-01 18:43 KST
-- 독자의 피드백 한 표. 종류 둘(ERROR_REPORT 오류 신고 · JUDGEMENT_REVIEW 판정 후기)과 본문을 받는다.
-- ★ 로그인 없이도 보낼 수 있어 user_id 는 비어 있을 수 있다. FK 는 걸지 않는다 — 계정을 지워도 피드백은 남긴다.
-- ★ 표 이름은 다른 도메인의 피드백 표(zzal_feedback · webtoon_feedback)와 같은 꼴이다.
-- ★ 파일 이름의 날짜 번호는 common/docs/git-convention.md 9절이다.

CREATE TABLE piece_maker_feedback (
    id          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind        varchar(20)  NOT NULL,                      -- ERROR_REPORT · JUDGEMENT_REVIEW
    body        text         NOT NULL,                      -- 2,000자까지. 서버가 검사한다
    user_id     bigint,                                     -- 로그인했으면 users.id, 아니면 NULL
    created_at  timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT ck_piece_maker_feedback_kind CHECK (kind IN ('ERROR_REPORT', 'JUDGEMENT_REVIEW'))
);

CREATE INDEX idx_piece_maker_feedback_kind_time ON piece_maker_feedback (kind, created_at);
CREATE INDEX idx_piece_maker_feedback_user ON piece_maker_feedback (user_id);
