-- haeun · 2026-09-26 00:01 KST
-- 목적: 웹툰 화면의 행동 기록을 남길 표를 만든다(#413).
--
-- ── 왜 공용 행동 기록(zzal_event)을 안 쓰나 ──────────────────────────
-- 공용 수집기(/api/v1/events)는 짤 화면을 기준으로 짜여 있다. 허용하는 값의
-- 키가 짤 화면에 맞춰져 있어서 웹툰이 알고 싶은 것(화질·보는 방식·어느 버튼)을
-- 담으려면 남의 목록을 계속 고쳐야 하고, 한 표에 섞이면 보관·파기 기준도 같이
-- 묶인다. 웹툰은 자기 표를 따로 둔다.
--
-- ── 무엇을 안 담나 ─────────────────────────────────────────────────
-- 사람이 쓴 글(이름·설명·메모·본문·이메일)은 이 표에 들어올 자리가 없다.
-- props 는 서버가 허용한 키만, 값은 짧은 기호(영문·숫자·밑줄 등)와 숫자·참거짓만
-- 남긴다(EventService). IP 와 브라우저 원문도 안 남긴다 — 기기는 mobile/desktop 둘로만.
--
-- ── 얼마나 두나 ────────────────────────────────────────────────────
-- 처리방침 제4조 「이용 흐름 분석 기록 1년」. 1년 지난 줄은 매일 지우고
-- (EventRetention), 탈퇴한 사람의 줄은 계정을 지울 때 함께 지운다(WebtoonEventPurge).

CREATE TABLE IF NOT EXISTS webtoon_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 무엇을 했나. 화면이 부르는 이름 그대로(예: next_episode_click).
    name         VARCHAR(60)  NOT NULL,
    -- 이 브라우저. 웹툰 화면이 이미 쓰는 localStorage 의 lore_uid 다.
    uid          VARCHAR(64),
    -- 로그인했으면 계정 번호.
    user_id      BIGINT,
    -- 그때 보고 있던 화면(landing · create · running · result …).
    view         VARCHAR(30),
    -- 허용된 키만 남긴 JSON.
    props        TEXT,
    -- mobile · desktop.
    device       VARCHAR(10),
    -- 유입 출처(utm_source 등). 첫 방문의 것만 화면이 싣는다.
    source       VARCHAR(100),
    -- 들어오기 전 주소의 호스트만(경로·쿼리는 떼어 낸다).
    ref_host     VARCHAR(100),
    -- 화면에서 일어난 시각. 말이 안 되는 값이면 받은 시각으로 대신한다.
    occurred_at  TIMESTAMPTZ  NOT NULL,
    received_at  TIMESTAMPTZ  NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_webtoon_event_name_time ON webtoon_event (name, occurred_at);
CREATE INDEX IF NOT EXISTS idx_webtoon_event_uid ON webtoon_event (uid);
CREATE INDEX IF NOT EXISTS idx_webtoon_event_user ON webtoon_event (user_id);
CREATE INDEX IF NOT EXISTS idx_webtoon_event_received ON webtoon_event (received_at);
