-- haeun · 2026-09-26 01:09 KST
-- 목적: 작품 찜(좋아요)을 담을 표를 만든다(#247).
--
-- 계정당 작품 하나에 한 줄이다. 같은 사람이 두 번 눌러도 한 줄이라 (run_id, user_id)
-- 를 유일하게 둔다. 로그인 안 한 사람은 찜할 수 없다 — 브라우저 번호(uid)로 받으면
-- 남의 번호를 적어 보낼 수 있고, 찜 수가 부풀면 둘러보기를 속일 수 있다.
--
-- 작품(webtoon_work)과 외래키로 묶지 않는다. 작품 표는 run_id 로 여러 줄(회차)이
-- 있을 수 있어 참조 대상이 하나가 아니고, 계정을 지울 때는 지우는 쪽이 이 표도
-- 같이 비운다(WebtoonPurge).

CREATE TABLE IF NOT EXISTS webtoon_run_like (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id      VARCHAR(64) NOT NULL,
    user_id     BIGINT      NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_webtoon_run_like UNIQUE (run_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_webtoon_run_like_user ON webtoon_run_like (user_id, created_at);
