-- haeun · 2026-09-26 KST
-- 목적: 공유 카드 링크로 남이 들어온 것을 세고, 카드 주인에게 무료 횟수를 돌려준다(#332).
--
-- 한 줄이 방문 한 번이다. (카드, 본 사람) 이 유일해서 같은 사람이 여러 번 열어도 한 줄이다.
-- 본 사람은 브라우저 번호(lore_uid)가 있으면 그것, 없으면 IP 해시다 — 주소 원문은 남기지 않는다.
--
-- rewarded 가 true 인 줄이 무료 횟수 한 번이다. 카드마다 상한(코드 상수)까지만 rewarded 로 적히고,
-- 그 뒤 방문은 세기만 한다. 주인이 그 횟수를 쓰면 used_at 이 찍힌다 — 지우지 않고 남겨 두어야
-- "몇 명이 봤고 몇 번을 받았나" 를 나중에도 셀 수 있다.

CREATE TABLE IF NOT EXISTS webtoon_share_visit (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 어느 카드. webtoon_character.public_id
    character_id  VARCHAR(40)  NOT NULL,
    -- 본 사람. "uid:<lore_uid>" 또는 "ip:<해시>"
    viewer_key    VARCHAR(80)  NOT NULL,
    -- 이 방문이 무료 횟수 한 번이 되었나(카드 상한 안이었나)
    rewarded      BOOLEAN      NOT NULL DEFAULT FALSE,
    -- 주인이 그 횟수를 쓴 때. 비어 있으면 아직 안 쓴 것
    used_at       TIMESTAMPTZ,
    opened_at     TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_webtoon_share_visit_once UNIQUE (character_id, viewer_key)
);

CREATE INDEX IF NOT EXISTS idx_webtoon_share_visit_character ON webtoon_share_visit (character_id);
