/* eslint-disable */
/**
 * 자동 생성 — Piece Maker 전용 API 계약 대조용 타입. 손으로 편집하지 않는다.
 * 생성: ./piece-maker/scripts/gen-api-types.sh
 * 원본: piece-maker/be/src/test/resources/openapi.json
 * 원본은 시험 전용 springdoc 그룹이 실제로 생성한다. 공용 전체 API 스냅샷과는 범위가 다르다.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/piece-maker/v1/ad-landings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 광고 URL 최초 수신 기록
         * @description 실제 광고 URL 진입 때 호출한다. 같은 쿠키와 requestKey의 재시도는 최초 서버 시각을 유지한다. 광고 정보를 바꾸거나 expectedUserId가 현재 인증과 다르면 409. 새 기록의 로그인 계정은 즉시 귀속하지만, 기존 익명 기록은 별도 claim으로 연결한다. 분석 비활성화는 쿠키 발급·저장 없이 409. 잘못된 본문은 400, 쿠키별 분당 상한은 429, DB 실패는 5xx이며 다시 시도할 수 있다.
         */
        post: operations["capture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piece-maker/v1/ad-landings/{id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 이번 광고 방문을 로그인 계정에 연결
         * @description 기존 익명 쿠키와 서버 발급 landingId가 모두 일치해야 한다. expectedUserId가 인증 계정과 다르면 409이며 변경하지 않는다. 다른 계정이 같은 방문을 요구하면 원래 소유자는 유지하되 모호함을 표시해 집계에서 제외한다. 쿠키나 기록이 없으면 404. 새 쿠키를 발급하거나 과거 익명 이벤트 전체를 연결하지 않는다.
         */
        post: operations["claim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piece-maker/v1/admin/ad-cohort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 광고 첫 유입 후 24시간 정상 열람 집계
         * @description 운영자 전용 읽기 API. campaign은 영문·숫자·점·밑줄·하이픈 1~64자, from/to/asOf는 ISO-8601 시각이다.
         *     from은 포함, to는 제외하며 from < to <= asOf <= 현재, 조회 기간은 최대 31일이다. asOf 생략 시 현재를 쓴다.
         *     계정별 최초로 연결된 광고 유입을 전체 이력에서 고른 뒤 캠페인·기간으로 거른다. 계정별 중복은 없다.
         *     기존 제출자·이전 정상 열람자·관리자·탈퇴자·설정한 테스트 계정·모호한 연결은 제외한다.
         *     만료·선택 삭제·수집 검증 공백으로 신규 여부를 판단할 수 없는 계정은 HISTORY_UNVERIFIABLE로 제외한다.
         *     history에는 실제 조회 시점의 보관 범위와 운영 검증으로 설정한 연속 수집 구간을 반환한다.
         *     보관 범위를 벗어난 from은 400이다. 오래된 asOf로 삭제 자료를 복원하지 않는다.
         *     24시간 이내(경계 포함) 첫 정상 열람, 관찰 중, 기간 내 미완료를 구분한다.
         *     계정 연결이 없거나 모호한 유입 수는 계정 수와 별도로 반환한다. 계정번호나 개인정보는 반환하지 않는다.
         *     서버 수신 시각에 근거한 내부 UTM 집계이며 Meta 기여 전환 보고서가 아니다.
         *     수집이 중지되어도 저장된 이력을 조회할 수 있고 collectionEnabled=false로 표시한다.
         */
        get: operations["report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piece-maker/v1/admin/hypotheses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 판정 안 된 가설 가져가기
         * @description `judgementStatus` 가 `PENDING` 인 가설을 **맡긴 순서(오래된 것이 앞)**로 준다. 먼저 맡긴 독자가 먼저 판정을 받는다.
         *     운영자가 `judge.py` 를 돌리기 전에 부른다.
         *     - 한 줄에 `judge.py` 의 입력이 다 든다 — `chapter` · `claim` · `cards[]`(복사한 카드) · `notes{}` · 해시 둘
         *     - 해시 둘은 독자가 맡길 때의 값이다. `judge.py` 가 자기 파일과 같은 자료인지 이 값으로 본다
         *     - 운영자가 아니면 403(ADMIN_ONLY). 없으면 빈 배열
         */
        get: operations["pending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piece-maker/v1/admin/hypotheses/judge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 판정 넣기
         * @description `judge.py` 가 끝난 뒤 결과를 넣는다. `id` 의 줄을 찾아 판정 칸을 채우고 `judgementStatus` 를 바꾸고 `judgedAt` 을 찍는다.
         *     - `COMPLETE` 면 `judgement` 필수(grade · reason · support · against — `cited_cards` 도 그대로 실린다). `presentation` 은 있을 때만
         *     - `FAILED` 면 `failureMessage` 필수(독자에게 보인다). **맡길 때 깎은 크레딧을 돌려준다** — 같은 가설에 두 번 넣어도 한 번만
         *     - **이미 판정한 가설도 덮어쓴다** — 다시 돌린 결과를 넣을 수 있게
         *     - 몸통의 `id` 는 lore 의 요청 id 다. judge.py 의 `request_id`(입력의 해시)가 아니다
         *     - 없는 `id` 는 404(PIECE_MAKER_HYPOTHESIS_NOT_FOUND). 운영자가 아니면 403(ADMIN_ONLY). 모양이 틀리면 400(INVALID_INPUT)
         */
        post: operations["judge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piece-maker/v1/hypotheses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 가설 맡기기
         * @description 독자가 "가설 판정하기"를 누르면 부른다. 저장이 곧 맡기기다 — 서버는 줄을 넣고 `judgementStatus` 를
         *     `PENDING` 으로 둔다. 판정은 운영자가 따로 돌려 넣는다. 화면은 응답의 `id` 로 되묻는다.
         *     - 담은 카드는 그 회차 N 으로 가린 값으로 **복사해 둔다**. 뒤에 카드 표가 바뀌어도 이 가설의 카드는 그대로다
         *     - 맡긴 뒤에는 제목 · 주장 · 카드 · 해석을 고칠 수 없다. 새 가설은 새로 맡긴다
         *     - `stateDigest` · `cardsDigest` 가 카드 표의 값과 다르면 400(PIECE_MAKER_DIGEST_MISMATCH) — 페이지를 새로 열어야 한다
         *     - 회차가 없거나 범위 밖이면 400(PIECE_MAKER_INVALID_CHAPTER). 카드 표가 비어 있으면 503(PIECE_MAKER_LEDGER_NOT_LOADED)
         *     - **맡길 때 크레딧을 깎는다** — 값은 `GET /public/cards/meta` 의 `judgeCredits`(지금 5). 모자라면 402(CREDIT_NOT_ENOUGH)
         *       에 필요 · 보유를 적어 주고 **저장하지 않는다**. 운영자가 FAILED 를 넣으면 돌려준다
         *     - 주장이 비었거나, 카드가 없거나 겹치거나 N화 기록에 없거나, 해석이 담지 않은 카드의 것이거나,
         *       글이 위 끝(제목 180 · 주장 6,000 · 해석 4,000자)을 넘으면 400(INVALID_INPUT)에 무엇이 틀렸는지 적어 준다
         */
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piece-maker/v1/hypotheses/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 가설 보관함
         * @description 로그인한 독자가 맡긴 가설을 **최신이 앞**으로 준다. 목록에 필요한 칸만 든다 — 카드와 판정은 하나를 눌러 2-6 으로 받는다.
         *     - 판정을 맡기지 않고 저장만 하는 가설은 서버에 없다(브라우저 임시 저장). 여기 오는 것은 모두 맡긴 가설이다
         *     - 없으면 빈 배열
         */
        get: operations["my"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piece-maker/v1/hypotheses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 가설 하나와 판정 되묻기
         * @description 맡긴 가설을 요청 id 로 연다. 보관함에서 하나를 열 때, 판정을 맡긴 뒤 결과를 되물을 때 부른다.
         *     몇 초마다 되물을지는 화면이 정한다 — 판정은 운영자가 따로 넣어서 시간이 걸린다.
         *     - `judgementStatus` 가 `PENDING` 이면 판정 칸 셋은 null
         *     - `COMPLETE` 면 `judgement`(judge.py 출력 그대로 — grade · reason · support · against · cited_cards)와
         *       `presentation`(편집본. 없을 수 있음), `judgedAt`
         *     - `FAILED` 면 독자에게 보일 `failureMessage`
         *     - 없는 번호와 **남의 가설은 같은 404**(PIECE_MAKER_HYPOTHESIS_NOT_FOUND) — 번호를 바꿔 가며 남의 가설을 찾아낼 수 없다
         */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piece-maker/v1/hypotheses/{id}/result-view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 첫 정상 판정 열람 기록
         * @description 로그인한 독자의 정상 판정이 활성 탭의 화면에 실제로 보였을 때 부른다. 요청 몸통은 없다.
         *     서버는 소유자와 COMPLETE 상태 및 판정 형식을 검사하고 계정당 보관 범위의 첫 한 줄만 저장한다.
         *     보관 중 새 탭·재열람·동시 요청은 firstView=false와 기존 viewedAt을 돌려준다. 만료 뒤에는 새 기록이 될 수 있다.
         *     firstView=true는 생애 최초나 신규 광고 전환을 뜻하지 않는다. DB 저장 실패는 성공으로 답하지 않는다.
         *     app.analytics.enabled=false이면 409로 답하며 기록하지 않는다. 같은 설정에서는 재시도하지 않는다.
         *     viewedAt은 최초 저장 시 서버가 기록한 시각이다. 기능 도입 전 열람 이력을 복원하지 않는다.
         *     이 기록은 광고 24시간 성과 집계 그 자체가 아니다.
         *     Meta 설정과 시험 계정 검토가 완료된 경우, 제외 대상이 아닌 첫 저장 응답에만 metaEvent를 발급한다.
         *     metaEvent는 광고 출처와 무관한 보관 기록상 첫 정상 열람 신호이며 Meta 수신·광고 기여를 보장하지 않는다.
         *     응답 유실·픽셀 차단 시 내부 열람은 유지되지만 Meta 신호는 누락될 수 있다.
         */
        post: operations["record"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piece-maker/v1/public/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 카드 목록과 검색
         * @description 독자가 읽은 회차 N 이하에 심은 카드를 표의 id 순(= T 번호 순)으로 나눠 준다.
         *     N화 뒤에 회수된 복선은 status=open, resolvedChapter=null, resolution=null 로 가려서 준다.
         *
         *     검색 규칙은 화면이 브라우저에서 찾던 것과 같다.
         *     · search 가 T12 꼴이면 그 번호의 카드 한 장만(대소문자 무관)
         *     · 그 밖에는 빈칸으로 나눈 단어가 모두 카드의 글(id · 제목 · 본문 · 인물 · 유형 · "12화")에 들어 있어야 한다.
         *       소문자로 바꾸고 빈칸을 없애고 견준다. % 와 _ 는 글자 그대로 찾는다
         *     · kind 는 유형의 한국어 이름이 똑같은 카드만. 검색어와 함께 건다
         *
         *     chapter 가 없거나 숫자가 아니거나 1~maxChapter 를 벗어나면 400(PIECE_MAKER_INVALID_CHAPTER).
         *     search 가 200자 또는 단어 10개를 넘거나 page · size 가 틀리면 400(INVALID_INPUT).
         */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piece-maker/v1/public/cards/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 장부 정보
         * @description 화면을 열 때 한 번 부른다. 가장 뒤 회차, 해시 둘, 유형 다섯, 권하는 인물 다섯을 준다.
         *
         *     카드를 50장씩 나눠 받으면 첫 쪽에 유형과 인물이 다 없고, 해시는 첫 쪽을 받기 전에 있어야
         *     브라우저 저장 키를 만들 수 있다. 그래서 카드와 상관없는 값을 따로 준다.
         *
         *     카드 표가 비어 있으면 503(PIECE_MAKER_LEDGER_NOT_LOADED). 운영 DB 에 카드 SQL 을 넣기 전이다.
         */
        get: operations["meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piece-maker/v1/public/cards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 카드 상세
         * @description 카드 한 장을 번호로 연다. 게시글에 적힌 번호로 카드를 열 때 부른다.
         *     목록이 준 카드에는 상세의 칸이 다 있어서, 목록에서 여는 상세는 이 API 를 부르지 않는다.
         *
         *     회수 칸 셋은 목록과 같은 규칙으로 N 기준으로 가린다.
         *     모르는 번호와 N화 뒤에 심은 카드는 같은 404(PIECE_MAKER_CARD_NOT_FOUND)다 — 구분해 주면
         *     번호를 바꿔 가며 뒤 회차의 카드가 있는지 알아낼 수 있다.
         */
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piece-maker/v1/public/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 피드백 보내기
         * @description 독자가 오류를 신고하거나 판정 후기를 남길 때 부른다. 로그인 없이도 보낼 수 있다.
         *     - `kind` 는 `ERROR_REPORT`(오류 신고) 또는 `JUDGEMENT_REVIEW`(판정 후기). 다른 값이면 400(INVALID_INPUT)
         *     - `body` 는 앞뒤 빈칸을 뗀 뒤 1자 이상 2,000자까지. 비었거나 넘으면 400(INVALID_INPUT)
         *     - 로그인한 상태로 보내면 누가 보냈는지 함께 적는다. 응답에는 보낸 사람을 싣지 않는다
         *     - 보낸 뒤에는 고칠 수 없다. 서버는 받았다는 뜻으로 저장된 줄을 돌려준다
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountCounts: {
            /** Format: int64 */
            completed?: number;
            /** Format: int64 */
            eligible?: number;
            /** Format: int64 */
            excluded?: number;
            /** Format: int64 */
            firstAttributed?: number;
            /** Format: int64 */
            noCompletion?: number;
            /** Format: int64 */
            pending?: number;
        };
        AdCohortReport: {
            accounts?: components["schemas"]["AccountCounts"];
            /** Format: date-time */
            asOf?: string;
            basis?: components["schemas"]["Basis"];
            campaign?: string;
            collectionEnabled?: boolean;
            creatives?: components["schemas"]["CreativeCounts"][];
            exclusions?: components["schemas"]["ExclusionCount"][];
            /** Format: date-time */
            from?: string;
            history?: components["schemas"]["PieceMakerAdMeasurementHistory"];
            observationWindowClosed?: boolean;
            provisional?: boolean;
            receipts?: components["schemas"]["ReceiptCounts"];
            testExclusionsReviewed?: boolean;
            /** Format: date-time */
            to?: string;
        };
        ApiResponseAdCohortReport: {
            data?: components["schemas"]["AdCohortReport"];
            error?: components["schemas"]["ErrorBody"];
            message?: string;
            success?: boolean;
        };
        ApiResponseForeshadowing: {
            data?: components["schemas"]["Foreshadowing"];
            error?: components["schemas"]["ErrorBody"];
            message?: string;
            success?: boolean;
        };
        ApiResponseForeshadowingMeta: {
            data?: components["schemas"]["ForeshadowingMeta"];
            error?: components["schemas"]["ErrorBody"];
            message?: string;
            success?: boolean;
        };
        ApiResponseForeshadowingPage: {
            data?: components["schemas"]["ForeshadowingPage"];
            error?: components["schemas"]["ErrorBody"];
            message?: string;
            success?: boolean;
        };
        ApiResponsePieceMakerAdLanding: {
            data?: components["schemas"]["PieceMakerAdLanding"];
            error?: components["schemas"]["ErrorBody"];
            message?: string;
            success?: boolean;
        };
        ApiResponsePieceMakerAdLandingClaim: {
            data?: components["schemas"]["PieceMakerAdLandingClaim"];
            error?: components["schemas"]["ErrorBody"];
            message?: string;
            success?: boolean;
        };
        ApiResponsePieceMakerFeedback: {
            data?: components["schemas"]["PieceMakerFeedback"];
            error?: components["schemas"]["ErrorBody"];
            message?: string;
            success?: boolean;
        };
        ApiResponsePieceMakerHypothesis: {
            data?: components["schemas"]["PieceMakerHypothesis"];
            error?: components["schemas"]["ErrorBody"];
            message?: string;
            success?: boolean;
        };
        ApiResponsePieceMakerHypothesisList: {
            data?: components["schemas"]["PieceMakerHypothesisList"];
            error?: components["schemas"]["ErrorBody"];
            message?: string;
            success?: boolean;
        };
        ApiResponsePieceMakerPendingHypothesisList: {
            data?: components["schemas"]["PieceMakerPendingHypothesisList"];
            error?: components["schemas"]["ErrorBody"];
            message?: string;
            success?: boolean;
        };
        ApiResponsePieceMakerResultView: {
            data?: components["schemas"]["PieceMakerResultView"];
            error?: components["schemas"]["ErrorBody"];
            message?: string;
            success?: boolean;
        };
        Basis: {
            accountState?: string;
            attribution?: string;
            completion?: string;
            landingTime?: string;
            limitations?: string[];
        };
        CreativeCounts: {
            adId?: string;
            /** Format: int64 */
            completed?: number;
            /** Format: int64 */
            eligible?: number;
            /** Format: int64 */
            noCompletion?: number;
            /** Format: int64 */
            pending?: number;
            placement?: string;
        };
        ErrorBody: {
            code?: string;
            message?: string;
        };
        ExclusionCount: {
            /** Format: int64 */
            accounts?: number;
            reason?: string;
        };
        /** @description 복선 카드 한 장. 회수 칸 셋(status · resolvedChapter · resolution)은 독자가 읽은 회차 N 기준으로 가린 값이다 */
        Foreshadowing: {
            /**
             * Format: int32
             * @description 복선을 심은 회차
             * @example 12
             */
            chapter?: number;
            /** @description 장부의 원문(영어) */
            excerpt?: string;
            /** @description 카드 본문 */
            fact?: string;
            /**
             * @description 카드 번호. 담기·상세·판정 요청의 열쇠
             * @example T12
             */
            id?: string;
            /**
             * @description 유형의 한국어 이름
             * @example 약속
             */
            kind?: string;
            /** @description 인물 이름. 없으면 빈 배열 */
            people?: string[];
            /** @description 회수 기록의 글. 미회수(또는 N화 뒤 회수)면 null */
            resolution?: string;
            /**
             * Format: int32
             * @description 회수된 회차. 미회수(또는 N화 뒤 회수)면 null
             * @example 214
             */
            resolvedChapter?: number;
            /**
             * @description 연결된 장면의 번호. 없으면 null
             * @example V12
             */
            scene?: string;
            /** @description 장면의 글. 없으면 빈 글 */
            sceneExcerpt?: string;
            /**
             * @description open 또는 resolved. N화 뒤에 회수된 복선은 open 으로 온다
             * @enum {string}
             */
            status?: "open" | "resolved";
            /** @description 카드 제목 */
            title?: string;
        };
        /** @description 장부 정보. 화면을 열 때 한 번 받는다 */
        ForeshadowingMeta: {
            /** @description 400화 카드 파일의 sha256. 위와 같다 */
            cardsDigest?: string;
            /**
             * Format: int32
             * @description 판정 1회에 깎는 크레딧. 맡길 때(2-5) 깎고 운영자가 FAILED 를 넣으면 돌려준다
             * @example 5
             */
            judgeCredits?: number;
            /** @description 유형의 한국어 이름. 카드에 먼저 나온 순서 */
            kinds?: string[];
            /**
             * Format: int32
             * @description 고를 수 있는 가장 뒤 회차
             * @example 400
             */
            maxChapter?: number;
            /** @description 400화 장부 파일의 sha256. 브라우저 저장 키와 판정 요청에 실린다 */
            stateDigest?: string;
            /** @description 검색창 아래에 권하는 인물. 카드에 먼저 나온 다섯 */
            suggestedPeople?: string[];
        };
        /** @description 카드 목록 한 쪽. chapter · page · size 는 요청한 값 그대로다 — 늦게 온 응답을 화면이 버리는 기준 */
        ForeshadowingPage: {
            /**
             * Format: int32
             * @description 요청한 회차 N
             * @example 200
             */
            chapter?: number;
            /**
             * Format: int64
             * @description N화 카드의 전체 수(검색어와 유형을 걸기 전)
             * @example 774
             */
            chapterTotal?: number;
            /** @description 다음 쪽이 있나 */
            hasNext?: boolean;
            /** @description 카드. 순서는 표의 id 순 = T 번호 순 */
            items?: components["schemas"]["Foreshadowing"][];
            /**
             * Format: int32
             * @description 요청한 쪽. 0부터
             * @example 0
             */
            page?: number;
            /**
             * Format: int32
             * @description 요청한 크기
             * @example 50
             */
            size?: number;
            /**
             * Format: int64
             * @description 찾은 카드의 수(검색어와 유형을 건 뒤)
             * @example 12
             */
            total?: number;
        };
        PieceMakerAdAttribution: {
            /** Format: int64 */
            firstAdLandedAt?: number;
            placement?: string;
            utmCampaign?: string;
            utmContent?: string;
            utmMedium?: string;
            utmSource?: string;
        };
        /** @description 광고 URL의 최초 서버 수신. 실제 광고 클릭을 외부 검증한 기록은 아님 */
        PieceMakerAdLanding: {
            /** Format: date-time */
            landedAt?: string;
            /** Format: uuid */
            landingId?: string;
        };
        PieceMakerAdLandingClaim: {
            /** Format: date-time */
            landedAt?: string;
            linked?: boolean;
        };
        PieceMakerAdLandingClaimRequest: {
            /** Format: int64 */
            expectedUserId: number;
        };
        PieceMakerAdLandingRequest: {
            attribution: components["schemas"]["PieceMakerAdAttribution"];
            /** Format: int64 */
            expectedUserId?: number;
            /** Format: uuid */
            requestKey: string;
        };
        PieceMakerAdMeasurementHistory: {
            /** Format: date-time */
            collectionVerifiedFrom?: string;
            /** Format: date-time */
            collectionVerifiedThrough?: string;
            /** Format: date-time */
            evaluatedAt?: string;
            /** Format: date-time */
            recordsAvailableAfter?: string;
            requestedWindowCovered?: boolean;
        };
        /** @description 저장된 피드백 하나 */
        PieceMakerFeedback: {
            /** @description 본문. 앞뒤 빈칸을 뗀 글 */
            body?: string;
            /**
             * Format: date-time
             * @description 받은 시각(UTC)
             * @example 2026-10-01T09:43:00Z
             */
            createdAt?: string;
            /**
             * Format: int64
             * @description 피드백 id
             * @example 3
             */
            id?: number;
            /**
             * @description 종류
             * @example JUDGEMENT_REVIEW
             * @enum {string}
             */
            kind?: "ERROR_REPORT" | "JUDGEMENT_REVIEW";
        };
        /** @description 피드백 보내기. 로그인 없이도 보낼 수 있다 */
        PieceMakerFeedbackCreate: {
            /**
             * @description 본문. 2,000자까지. 비면 400
             * @example 인용한 카드가 제 가설과 맞지 않았어요
             */
            body?: string;
            /**
             * @description 종류. ERROR_REPORT(오류 신고) 또는 JUDGEMENT_REVIEW(판정 후기)
             * @example JUDGEMENT_REVIEW
             * @enum {string}
             */
            kind?: "ERROR_REPORT" | "JUDGEMENT_REVIEW";
        };
        /** @description 가설 하나. 맡기기 · 되묻기 · 판정 넣기의 응답이 모두 이 모양이다 */
        PieceMakerHypothesis: {
            /** @description 맡길 때 복사한 카드. 칸은 카드 API 의 열둘, 회수 칸은 N화로 가린 값. 순서 그대로 */
            cards?: components["schemas"]["Foreshadowing"][];
            /**
             * Format: int32
             * @description 독자가 읽은 회차 N
             * @example 200
             */
            chapter?: number;
            /** @description 독자의 주장 */
            claim?: string;
            /**
             * Format: date-time
             * @description 맡긴 때(UTC)
             */
            createdAt?: string;
            /** @description 독자에게 보일 실패 문구. FAILED 일 때만 */
            failureMessage?: string | null;
            /**
             * Format: int64
             * @description 요청 id. 되묻기와 보관함의 열쇠
             * @example 17
             */
            id?: number;
            /**
             * Format: date-time
             * @description 판정을 넣은 때(UTC). PENDING 이면 null
             */
            judgedAt?: string | null;
            /** @description 판정. judge.py 출력 그대로(grade · reason · support · against · cited_cards). COMPLETE 일 때만 */
            judgement?: {
                [key: string]: unknown;
            } | null;
            /**
             * @description 판정 상태
             * @example PENDING
             * @enum {string}
             */
            judgementStatus?: "PENDING" | "COMPLETE" | "FAILED";
            /** @description 카드 번호마다 독자의 해석. 담은 카드마다 한 칸(없으면 빈 글) */
            notes?: {
                [key: string]: string;
            };
            /** @description 편집본. COMPLETE 이고 편집본이 있을 때만 */
            presentation?: {
                [key: string]: unknown;
            } | null;
            /** @description 제목. 없으면 빈 글 */
            title?: string;
        };
        /** @description 운영자가 판정을 넣는다. judge.py 출력을 그대로 싣는다. 이미 판정한 가설이면 덮어쓴다 */
        PieceMakerHypothesisJudge: {
            /** @description 독자에게 보일 실패 문구. FAILED 면 필수 */
            failureMessage?: string | null;
            /**
             * Format: int64
             * @description 판정한 가설의 요청 id(2-8 의 items[].id). judge.py 의 request_id 가 아니다
             * @example 17
             */
            id?: number;
            /** @description judge.py 출력의 judgement(grade · reason · support · against · cited_cards). COMPLETE 면 필수 */
            judgement?: {
                [key: string]: unknown;
            } | null;
            /**
             * @description COMPLETE 또는 FAILED
             * @example COMPLETE
             * @enum {string}
             */
            judgementStatus?: "COMPLETE" | "FAILED";
            /** @description 편집본(editor 출력). 있을 때만 */
            presentation?: {
                [key: string]: unknown;
            } | null;
        };
        /** @description 내 가설 보관함. 최신이 앞이다 */
        PieceMakerHypothesisList: {
            /** @description 맡긴 가설. 없으면 빈 배열 */
            items?: components["schemas"]["PieceMakerHypothesisSummary"][];
        };
        /** @description 가설 맡기기. 저장이 곧 맡기기다 — 서버는 PENDING 으로 두고 운영자가 판정을 넣는다 */
        PieceMakerHypothesisSubmit: {
            /**
             * @description 담은 카드의 번호. 하나 이상 100장까지. 겹치지 않음. 배열 순서가 근거의 순서
             * @example [
             *       "T2",
             *       "T374"
             *     ]
             */
            cards?: string[];
            /** @description 장부 정보(cards/meta)의 cardsDigest. 위와 같다 */
            cardsDigest?: string;
            /**
             * Format: int32
             * @description 독자가 읽은 회차 N. 1부터 장부의 가장 뒤 회차까지
             * @example 200
             */
            chapter?: number;
            /** @description 독자의 주장. 6,000자까지. 비면 400 */
            claim?: string;
            /** @description 카드 번호마다 독자의 해석. 4,000자까지. 담은 카드의 번호만 열쇠로 온다 */
            notes?: {
                [key: string]: string;
            };
            /** @description 재시도 식별 UUID. 같은 키와 같은 입력은 한 번만 접수·차감한다 */
            requestKey?: string | null;
            /** @description 장부 정보(cards/meta)의 stateDigest. 카드 표의 값과 다르면 400 PIECE_MAKER_DIGEST_MISMATCH */
            stateDigest?: string;
            /** @description 가설 제목. 180자까지. 비어도 된다 */
            title?: string;
        };
        /** @description 보관함의 한 줄. 누르면 가설 하나(2-6)를 받는다 */
        PieceMakerHypothesisSummary: {
            /**
             * Format: int32
             * @description 독자가 읽은 회차 N
             * @example 200
             */
            chapter?: number;
            /**
             * Format: date-time
             * @description 맡긴 때(UTC)
             */
            createdAt?: string;
            /**
             * Format: int64
             * @description 요청 id
             * @example 17
             */
            id?: number;
            /**
             * Format: date-time
             * @description 판정을 넣은 때(UTC). PENDING 이면 null
             */
            judgedAt?: string | null;
            /**
             * @description 판정 상태
             * @example PENDING
             * @enum {string}
             */
            judgementStatus?: "PENDING" | "COMPLETE" | "FAILED";
            /** @description 제목. 없으면 빈 글 */
            title?: string;
        };
        /** @description 브라우저가 한 번 시도할 PM 전용 이벤트. Meta 수신이나 광고 기여를 뜻하지 않는다 */
        PieceMakerMetaPixelEvent: {
            eventId?: string;
            eventName?: string;
            pixelId?: string;
            siteOrigin?: string;
        };
        /** @description 판정 안 된 가설 한 줄. judge.py 의 입력이 그대로 든다 */
        PieceMakerPendingHypothesis: {
            /** @description 맡길 때 복사한 카드. 순서 그대로. judge.py 에는 id 만 넘긴다 */
            cards?: components["schemas"]["Foreshadowing"][];
            /** @description 맡길 때 카드 표의 cardsDigest */
            cardsDigest?: string;
            /**
             * Format: int32
             * @description 독자가 읽은 회차 N
             * @example 200
             */
            chapter?: number;
            /** @description 독자의 주장 */
            claim?: string;
            /**
             * Format: date-time
             * @description 맡긴 때(UTC). 이 순서로 온다
             */
            createdAt?: string;
            /**
             * Format: int64
             * @description 요청 id. 판정을 넣을 때(2-9) 이 값을 싣는다
             * @example 17
             */
            id?: number;
            /** @description 카드 번호마다 독자의 해석. 담은 카드마다 한 칸(없으면 빈 글) */
            notes?: {
                [key: string]: string;
            };
            /** @description 맡길 때 카드 표의 stateDigest. judge.py 가 자기 파일과 견준다 */
            stateDigest?: string;
            /** @description 제목. 없으면 빈 글 */
            title?: string;
        };
        /** @description 판정 안 된 가설. 오래된 것이 앞이다 */
        PieceMakerPendingHypothesisList: {
            /** @description 판정 안 된 가설. 없으면 빈 배열 */
            items?: components["schemas"]["PieceMakerPendingHypothesis"][];
        };
        /** @description 보관 중인 계정의 첫 정상 판정 열람 기록. 생애 최초나 광고 전환을 보장하지 않는다 */
        PieceMakerResultView: {
            /** @description 이번 요청으로 보관 범위의 첫 기록을 저장했으면 true. 만료 뒤에도 true가 될 수 있다 */
            firstView?: boolean;
            /** @description 전송 설정이 켜져 있고 대상인 첫 요청에만 발급. 운영자·시험 계정·불완전 이력·재열람은 null */
            metaEvent?: components["schemas"]["PieceMakerMetaPixelEvent"];
            /**
             * Format: date-time
             * @description 보관 중인 최초 기록 시각(UTC). 보관 중 재열람에는 바뀌지 않는다
             */
            viewedAt?: string;
        };
        ReceiptCounts: {
            /** Format: int64 */
            ambiguousLandings?: number;
            /** Format: int64 */
            unclaimedLandings?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capture: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PieceMakerAdLandingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerAdLanding"];
                };
            };
        };
    };
    claim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PieceMakerAdLandingClaimRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerAdLandingClaim"];
                };
            };
        };
    };
    report: {
        parameters: {
            query: {
                campaign: string;
                from: string;
                to: string;
                asOf?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdCohortReport"];
                };
            };
        };
    };
    pending: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 판정 안 된 가설. 오래된 것이 앞 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerPendingHypothesisList"];
                };
            };
            /** @description 로그인 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerPendingHypothesisList"];
                };
            };
            /** @description 운영자가 아님(ADMIN_ONLY) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerPendingHypothesisList"];
                };
            };
        };
    };
    judge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PieceMakerHypothesisJudge"];
            };
        };
        responses: {
            /** @description 판정을 넣은 가설(2-6 의 모양) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerHypothesis"];
                };
            };
            /** @description 모양이 틀림(INVALID_INPUT) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerHypothesis"];
                };
            };
            /** @description 로그인 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerHypothesis"];
                };
            };
            /** @description 운영자가 아님(ADMIN_ONLY) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerHypothesis"];
                };
            };
            /** @description 없는 id(PIECE_MAKER_HYPOTHESIS_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerHypothesis"];
                };
            };
        };
    };
    submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PieceMakerHypothesisSubmit"];
            };
        };
        responses: {
            /** @description 맡겼음. 저장된 가설(PENDING) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerHypothesis"];
                };
            };
            /** @description 입력이 틀림(INVALID_INPUT · PIECE_MAKER_INVALID_CHAPTER · PIECE_MAKER_DIGEST_MISMATCH) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerHypothesis"];
                };
            };
            /** @description 로그인 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerHypothesis"];
                };
            };
            /** @description 크레딧이 모자람(CREDIT_NOT_ENOUGH). 저장되지 않음 */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerHypothesis"];
                };
            };
            /** @description 카드 표가 비어 있음(PIECE_MAKER_LEDGER_NOT_LOADED) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerHypothesis"];
                };
            };
        };
    };
    my: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 보관함 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerHypothesisList"];
                };
            };
            /** @description 로그인 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerHypothesisList"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 요청 id. 맡길 때 받은 값
                 * @example 17
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 가설 하나 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerHypothesis"];
                };
            };
            /** @description 로그인 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerHypothesis"];
                };
            };
            /** @description 없는 번호 또는 남의 가설(PIECE_MAKER_HYPOTHESIS_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerHypothesis"];
                };
            };
        };
    };
    record: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 계정의 첫 열람 기록 또는 기존 기록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerResultView"];
                };
            };
            /** @description 정상 판정이 아님(INVALID_INPUT) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerResultView"];
                };
            };
            /** @description 로그인 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerResultView"];
                };
            };
            /** @description 없는 번호 또는 남의 가설(PIECE_MAKER_HYPOTHESIS_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerResultView"];
                };
            };
            /** @description 기록 비활성화(PIECE_MAKER_RESULT_VIEW_DISABLED). 저장되지 않았으며 재시도하지 않음 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerResultView"];
                };
            };
        };
    };
    list: {
        parameters: {
            query: {
                /**
                 * @description 독자가 읽은 회차 N. 1부터 maxChapter 까지
                 * @example 200
                 */
                chapter: number;
                /**
                 * @description 검색어. 200자 · 단어 10개까지. 비면 N화 카드 전부
                 * @example 밀짚모자
                 */
                search?: string;
                /**
                 * @description 유형의 한국어 이름. 비면 거르지 않는다
                 * @example 약속
                 */
                kind?: string;
                /**
                 * @description 쪽. 0부터. 기본 0
                 * @example 0
                 */
                page?: number;
                /**
                 * @description 한 쪽의 크기. 기본 50, 최대 100
                 * @example 50
                 */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseForeshadowingPage"];
                };
            };
        };
    };
    meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseForeshadowingMeta"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query: {
                /**
                 * @description 독자가 읽은 회차 N. 1부터 maxChapter 까지
                 * @example 200
                 */
                chapter: number;
            };
            header?: never;
            path: {
                /**
                 * @description 카드 번호
                 * @example T12
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseForeshadowing"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PieceMakerFeedbackCreate"];
            };
        };
        responses: {
            /** @description 저장됨 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerFeedback"];
                };
            };
            /** @description 입력이 틀림(INVALID_INPUT) — kind 가 둘 중 하나가 아니거나 body 가 비었거나 2,000자를 넘음 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePieceMakerFeedback"];
                };
            };
        };
    };
}
