-- 가설 표 둘 — 독자가 맡긴 가설(hypotheses)과 그때 담은 카드의 복사본(hypothesis_foreshadowing).
-- 명세는 NA migration/front_back_protocol.md 2-5~2-9, 초안은 cards_api.md 2절 끝(decisions.md 2-25).
--
-- ★ 저장이 곧 맡기기다(decisions.md 1-20). 줄이 생기면 judgement_status 는 PENDING 이고, 운영자가 judge.py 를
--   돌려 2-9 로 판정을 넣으면 COMPLETE/FAILED 가 된다. 서버는 판정하지 않는다(later.md 1-2).
-- ★ 담은 카드는 foreshadowings 를 가리키지 않고 복사한다(decisions.md 1-19). 카드 표를 갈아 넣어도 판정받은
--   가설의 근거는 그대로다. 복사하는 열둘은 카드 API(2-4)의 열둘이고, 회수 칸 셋은 그 회차 N 으로 가린 값이다.
-- ★ judgement · presentation 은 jsonb 다(decisions.md 1-22). judge.py 출력을 통째로 넣는다(cited_cards 포함, 1-29).
-- ★ 파일 이름의 날짜 번호는 common/docs/git-convention.md 9절이다.

CREATE TABLE hypotheses (
    id                bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 요청 id. 2-5 가 돌려주고 2-6 · 2-9 가 받는다
    user_id           bigint       NOT NULL REFERENCES users (id),               -- 맡긴 독자
    chapter           integer      NOT NULL,                                     -- 독자가 읽은 회차 N. judge.py 가 이 회차로 장부를 자른다
    title             varchar(180) NOT NULL DEFAULT '',
    claim             text         NOT NULL,                                     -- 6,000자까지. 서버가 검사한다
    state_digest      varchar(64)  NOT NULL,                                     -- 화면이 2-1 에서 받아 실은 값. 맡길 때 카드 표의 값과 같아야 한다
    cards_digest      varchar(64)  NOT NULL,
    judgement_status  varchar(16)  NOT NULL DEFAULT 'PENDING',
    judgement         jsonb,                                                     -- judge.py 출력 그대로. COMPLETE 일 때
    presentation      jsonb,                                                     -- 편집본. 있을 때만
    failure_message   text,                                                      -- FAILED 일 때 독자에게 보일 문구
    created_at        timestamptz  NOT NULL DEFAULT now(),
    judged_at         timestamptz,                                               -- 2-9 가 찍는다
    CONSTRAINT ck_hypotheses_status CHECK (judgement_status IN ('PENDING', 'COMPLETE', 'FAILED')),
    CONSTRAINT ck_hypotheses_judgement CHECK (
        (judgement_status = 'PENDING' AND judgement IS NULL AND failure_message IS NULL AND judged_at IS NULL)
        OR (judgement_status = 'COMPLETE' AND judgement IS NOT NULL AND judged_at IS NOT NULL)
        OR (judgement_status = 'FAILED' AND failure_message IS NOT NULL AND judged_at IS NOT NULL))
);
CREATE INDEX idx_hypotheses_user_created ON hypotheses (user_id, created_at DESC);                  -- 2-7 보관함: 독자별 최신순
CREATE INDEX idx_hypotheses_pending ON hypotheses (created_at) WHERE judgement_status = 'PENDING';  -- 2-8 운영자: PENDING 만 오래된 순

CREATE TABLE hypothesis_foreshadowing (
    id                    bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hypothesis_id         bigint      NOT NULL REFERENCES hypotheses (id) ON DELETE CASCADE,
    card_position         integer     NOT NULL,                -- 근거의 순서. 0부터. 요청 cards[] 의 순서(position 은 SQL·HQL 의 함수 이름이라 피했다)
    note                  text        NOT NULL DEFAULT '',     -- 독자의 해석. 4,000자까지. 요청 notes{}
    thread_id             varchar(16) NOT NULL,                -- 아래 열둘은 저장할 때 foreshadowings 에서 복사한다. 회수 칸 셋은 회차 N 으로 가린 값
    start_chapter         integer     NOT NULL,
    thread_kind           varchar(40) NOT NULL,
    title                 text        NOT NULL,
    fact                  text        NOT NULL,
    thread_related_people text        NOT NULL DEFAULT '',
    excerpt               text        NOT NULL,
    scene                 varchar(16),
    scene_excerpt         text        NOT NULL DEFAULT '',
    status                varchar(16) NOT NULL,
    resolved_chapter      integer,
    resolution            text,
    CONSTRAINT uk_hypothesis_foreshadowing_position UNIQUE (hypothesis_id, card_position),
    CONSTRAINT uk_hypothesis_foreshadowing_card UNIQUE (hypothesis_id, thread_id)
);
