-- 복선 카드 표. 400화 카드 1,651장을 한 줄에 한 장씩 넣는다(NarrativeAnalysis migration/cards_api.md 2절).
--
-- 카드 글은 이 파일에 없다. NA의 src/deliver/export_cards_sql.py 가 INSERT 문을 만들고, 그 파일은
-- lore 의 git 에 올리지 않는다(원작을 요약한 글 1,651건). 검사용 25장만 trailer/be/src/test/resources 에 있다.
--
-- ★ 회수 칸 셋(status · resolved_chapter · resolution)은 400화 기준의 값이다. 독자가 읽은 회차 N 뒤에
--   회수된 복선은 서버가 꺼낼 때 미회수로 가려서 준다(Foreshadowing.statusAt). DB 에는 원래 값을 둔다.
-- ★ 해시 둘은 줄마다 같은 값이다 — 400화 장부 파일과 카드 파일의 sha256. 판정(judge.py)이 자기 파일과
--   같은 자료인지 이 값으로 확인한다. char(64) 가 아니라 varchar(64) 인 이유: char 는 Hibernate 의 validate 가
--   String 과 다른 자료형으로 봐서 기동을 막는다.
CREATE TABLE foreshadowings (
    id                    bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- DB가 매기는 번호. 넣는 순서가 T 번호 순이라 목록은 이 번호 순으로 늘어놓는다(NA decisions.md 1-24)
    thread_id             varchar(16) NOT NULL,            -- "T12". 화면과 판정이 쓰는 이름
    start_chapter         integer     NOT NULL,            -- 복선을 심은 회차
    thread_type           varchar(40) NOT NULL,            -- 장부의 유형(영어). 화면도 판정도 읽지 않는다. 거르거나 셀 때 쓰려고 둔다
    thread_kind           varchar(40) NOT NULL,            -- 유형의 한국어 이름
    title                 text        NOT NULL,
    fact                  text        NOT NULL,
    thread_related_people text        NOT NULL DEFAULT '', -- 인물 이름을 줄바꿈으로 이은 글
    excerpt               text        NOT NULL,            -- 장부의 원문. 영어로 남는다
    scene                 varchar(16),                     -- 연결된 장면의 번호. 없으면 NULL
    scene_excerpt         text        NOT NULL DEFAULT '',
    status                varchar(16) NOT NULL,            -- 아래 셋은 400화 기준의 값. 꺼낼 때 가린다
    resolved_chapter      integer,
    resolution            text,
    search_text           text        NOT NULL,            -- 검색용 글. id·title·fact·인물·kind·"12화"를 잇고 소문자로 바꾸고 빈칸을 없앤 것. resolution 은 넣지 않는다(가린 회수 기록이 검색으로 새면 안 된다)
    state_digest          varchar(64) NOT NULL,            -- 400화 장부 파일의 sha256. 줄마다 같다
    cards_digest          varchar(64) NOT NULL,            -- 400화 카드 파일의 sha256. 줄마다 같다
    CONSTRAINT uk_foreshadowings_thread_id UNIQUE (thread_id),
    CONSTRAINT ck_foreshadowings_status CHECK (
        (status = 'open' AND resolved_chapter IS NULL AND resolution IS NULL)
        OR (status = 'resolved' AND resolved_chapter >= start_chapter AND resolution IS NOT NULL))
);
CREATE INDEX idx_foreshadowings_start_chapter ON foreshadowings (start_chapter);
