-- 후보 여러 판을 남긴다 + 굽기 골격을 버린다 (정본 6장 · 1.9)


-- ── 1) 굽기 골격을 버린다 ────────────────────────────────────────────────
--
-- ★ zzal_bake·zzal_bake_candidate 는 "밤 굽기가 아직 없다" 는 전제로 만든 새 모델이었다.
--   실제로는 zzal_motion 을 주인으로 하는 굽기 시스템이 이미 돌고 있었다(NightPlanner·NightSweep·
--   MotionService·AdminController). 두 모델을 같이 두면 한 동작이 두 번 구워지고, 상태가 두 곳에 적혀
--   한쪽만 고쳐도 아무 오류가 안 난다.
--
-- ★ 한 줄도 들어간 적이 없다 — bake 패키지 밖에서 참조가 0건이었다. 그래서 옮길 것이 없다.
-- ★ V7 은 히스토리에 그대로 둔다. 되감지 않고 여기서 지운다.

DROP TABLE IF EXISTS zzal_bake_candidate;
DROP TABLE IF EXISTS zzal_bake;


-- ── 2) 후보 한 판 ────────────────────────────────────────────────────────
--
-- ★★ 왜 필요한가 — zzal_motion 은 그림 키가 한 칸이라 <b>재생성이 앞의 판을 덮어썼다.</b>
--   정본 1.9 는 "나온 판을 전부 보여 주고 그중에서 고른다" 이다. 덮어쓰면 고를 수가 없고,
--   나중에 "어느 판이 사용자에게 나갔나" 도 알 수 없다.
--
-- ★ 한 모션에 최대 일곱 판이 달린다 — 서버 API 1판 + 맥미니 3판 x 2라운드.
-- ★ 게이트 판정을 지우지 않고 남긴다. 사람이 고른 것과 대조해야 게이트를 사람 눈에 맞춰 보정할 수 있다.

CREATE TABLE zzal_motion_candidate (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    motion_id bigint NOT NULL,
    -- 0 = 서버 API 판, 1~2 = 맥미니 CLI 라운드
    round integer DEFAULT 0 NOT NULL,
    -- API 판은 격자를 남기지 않을 수 있다(후처리만 올라온 경우)
    grid_key character varying(300),
    image_key character varying(300) NOT NULL,
    -- API · LOCAL
    source character varying(20) NOT NULL,
    -- PASS · REVIEW · FAIL
    gate_verdict character varying(20),
    gate_note character varying(300),
    gate_version character varying(20),
    -- 높은 것부터 위에 놓는 데 쓴다. 아직 안 쟀으면 비어 있다
    gate_score double precision,
    -- 사람이 이 판을 골랐나. 한 모션에 최대 하나
    chosen boolean DEFAULT false NOT NULL,
    created_at timestamp(6) with time zone NOT NULL
);

CREATE INDEX idx_zzal_motion_candidate_motion ON zzal_motion_candidate (motion_id);

-- ★ 한 모션에 고른 판은 하나뿐이다. 주석에만 두면 언젠가 둘이 된다.
CREATE UNIQUE INDEX uk_zzal_motion_candidate_chosen
    ON zzal_motion_candidate (motion_id) WHERE chosen;
