-- 행동 기록 보관 — 어디까지 S3 로 올렸는지 남기는 표.
--
-- ★★ 원본(zzal_event)은 손대지 않는다. 이 표는 <b>보관층의 영수증</b>일 뿐이고,
--   보관이 끝났다고 원본을 지우는 코드는 어디에도 없다. 알파 측정의 기준이 그 표다.
--
-- ★ 왜 "어디까지" 를 따로 적나 — 같은 줄을 두 번 올리지 않으려면 기준점이 있어야 하는데,
--   그 기준을 원본 표에 칸으로 달면 기록을 받는 쪽(AnalyticsService)이 보관의 사정을 알게 된다.
--   영수증을 따로 두면 원본은 읽기 전용으로 남고, 기준점은 max(to_event_id) 하나로 나온다.
--
-- ★ s3_key 에 유니크를 건다 — 같은 구간을 두 번 올리면 키가 같아지므로(키가 id 구간에서
--   결정적으로 나온다) 두 번째 기록이 DB 에서 막힌다. 올리는 쪽이 실수해도 영수증은 한 장이다.

CREATE TABLE zzal_event_archive_part (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 이 덩어리가 속한 날(received_at 을 KST 로 본 날짜). S3 경로의 dt= 와 같은 값이다.
    dt date NOT NULL,
    -- 이 덩어리가 담은 zzal_event.id 의 처음과 끝(양끝 포함).
    from_event_id bigint NOT NULL,
    to_event_id bigint NOT NULL,
    row_count integer NOT NULL,
    -- 올린 파일의 크기(압축 뒤 바이트). 보관 비용을 나중에 세려면 이 숫자가 필요하다.
    byte_size bigint NOT NULL,
    -- 어느 버킷의 어느 키로 갔나. 계정을 옮기면 버킷 이름이 바뀌므로 같이 적는다.
    bucket character varying(120) NOT NULL,
    s3_key character varying(300) NOT NULL,
    uploaded_at timestamp(6) with time zone NOT NULL,
    -- 어느 서버가 올렸나(호스트명). 두 대가 도는 날 로그 대조용.
    server character varying(60)
);

CREATE UNIQUE INDEX uq_zzal_event_archive_part_key ON zzal_event_archive_part (s3_key);
CREATE INDEX idx_zzal_event_archive_part_to ON zzal_event_archive_part (to_event_id);
