-- ★ 기준선(baseline) — 이 시점의 스키마 전체.
--
-- ★ 왜 있나 — `ddl-auto: validate` 로 바꾸면서 표를 만드는 일이 Hibernate 손을 떠났다.
--   빈 DB(새로 받은 팀원·CI)에서는 이 파일이 표를 전부 만든다. 없으면 서버가 아예 못 뜬다.
--
-- ★ 기존 DB 에서는 실행되지 않는다 — `baseline-version: 1` 이라, 이미 표가 있는 DB 에
--   Flyway 가 처음 붙을 때 "1번까지는 적용된 것으로 친다" 고 표시하고 V2 부터 적용한다.
--   그래서 이 파일이 이미 있는 표를 다시 만들려다 죽는 일이 없다.
--
-- ★ 손으로 고치지 않는다 — 스키마를 바꾸려면 V4, V5… 를 새로 만든다.
--   이미 적용된 파일을 고치면 Flyway 가 체크섬 불일치로 기동을 막는다(그게 안전장치다).
--
-- ★ 스키마 이름(public.)을 일부러 뺐다 — 박아 두면 Flyway 가 정한 스키마가 아니라
--   언제나 public 을 건드려, 다른 스키마로 시험하거나 옮길 수 없다.
--
-- ★ 새로 만드는 컬럼·표는 여기 넣지 않는다 — 이 파일은 기존 DB 에서 건너뛴다.
--   여기에만 넣으면 빈 DB 에만 생기고 기존 DB 에는 안 생겨, 배포에서 기동이 막힌다
--   (2026-09-09 실제로 겪었다). 스키마를 바꾸려면 새 번호 파일(V5, V6…)을 만든다.
--
-- 뜬 시각: 2026-09-09 · PostgreSQL 16.14 · 표 37개

--
--

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

--
-- Name: comic_character_sheet; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE comic_character_sheet (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    fail_reason character varying(500),
    name character varying(40),
    owner_key character varying(64) NOT NULL,
    sheet_image_key character varying(512),
    source_image_key character varying(512) NOT NULL,
    status character varying(16) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT comic_character_sheet_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'RUNNING'::character varying, 'READY'::character varying, 'FAILED'::character varying])::text[])))
);

--
-- Name: comic_feedback; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE comic_feedback (
    id uuid NOT NULL,
    comment character varying(1000),
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(200),
    owner_key character varying(64) NOT NULL,
    rating integer NOT NULL,
    job_id uuid
);

--
-- Name: comic_feedback_chip; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE comic_feedback_chip (
    feedback_id uuid NOT NULL,
    chip character varying(32),
    CONSTRAINT comic_feedback_chip_chip_check CHECK (((chip)::text = ANY ((ARRAY['UNNATURAL_MOTION'::character varying, 'NOT_LIKE_CHARACTER'::character varying, 'WANT_MORE_ACTIONS'::character varying, 'WANT_LONGER'::character varying, 'QUALITY_LOW'::character varying, 'TOO_SLOW'::character varying])::text[])))
);

--
-- Name: comic_gif_job; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE comic_gif_job (
    id uuid NOT NULL,
    action character varying(24) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    owner_key character varying(64) NOT NULL,
    status character varying(16) NOT NULL,
    updated_at timestamp(6) without time zone,
    sheet_id uuid NOT NULL,
    CONSTRAINT comic_gif_job_action_check CHECK (((action)::text = ANY ((ARRAY['WINK_HEART'::character varying, 'SURPRISE_JUMP'::character varying, 'SHY'::character varying, 'ROLL'::character varying, 'CLAP'::character varying, 'WAVE'::character varying, 'BOW'::character varying, 'FALL'::character varying, 'HOP'::character varying])::text[]))),
    CONSTRAINT comic_gif_job_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'RUNNING'::character varying, 'DONE'::character varying, 'FAILED'::character varying])::text[])))
);

--
-- Name: comic_gif_take; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE comic_gif_take (
    id uuid NOT NULL,
    attempts integer NOT NULL,
    fail_reason character varying(500),
    finished_at timestamp(6) without time zone,
    gif_image_key character varying(512),
    grid_image_key character varying(512),
    started_at timestamp(6) without time zone,
    status character varying(16) NOT NULL,
    take_no integer NOT NULL,
    job_id uuid NOT NULL,
    CONSTRAINT comic_gif_take_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'RUNNING'::character varying, 'DONE'::character varying, 'REJECTED'::character varying, 'FAILED'::character varying])::text[])))
);

--
-- Name: comic_usage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE comic_usage (
    id uuid NOT NULL,
    owner_key character varying(64) NOT NULL,
    take_count integer NOT NULL,
    usage_date date NOT NULL,
    bonus_takes integer DEFAULT 0 NOT NULL
);

--
-- Name: comics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE comics (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    description text,
    result_image_key character varying(255),
    title character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone
);

--
-- Name: comics_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE comics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME comics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: credit_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE credit_event (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    delta integer NOT NULL,
    domain character varying(20) NOT NULL,
    memo character varying(200),
    reason character varying(30) NOT NULL,
    ref_id character varying(100) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT credit_event_domain_check CHECK (((domain)::text = ANY ((ARRAY['COMMON'::character varying, 'WEBTOON'::character varying, 'ZZAL'::character varying, 'TRAILER'::character varying])::text[]))),
    CONSTRAINT credit_event_reason_check CHECK (((reason)::text = ANY ((ARRAY['WELCOME'::character varying, 'DAILY'::character varying, 'PURCHASE'::character varying, 'SPEND'::character varying, 'REFUND'::character varying, 'REWARD'::character varying, 'ADJUST'::character varying])::text[])))
);

--
-- Name: credit_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE credit_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME credit_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: upload_ticket; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE upload_ticket (
    id bigint NOT NULL,
    content_type character varying(100) NOT NULL,
    domain character varying(20) NOT NULL,
    issued_at timestamp(6) with time zone NOT NULL,
    s3_key character varying(300) NOT NULL,
    used_at timestamp(6) with time zone,
    user_id bigint NOT NULL
);

--
-- Name: upload_ticket_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE upload_ticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME upload_ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: user_agreement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE user_agreement (
    id bigint NOT NULL,
    agreed boolean NOT NULL,
    agreed_at timestamp(6) with time zone NOT NULL,
    type character varying(30) NOT NULL,
    version character varying(20) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT user_agreement_type_check CHECK (((type)::text = ANY ((ARRAY['AGE_14'::character varying, 'TERMS'::character varying, 'PRIVACY'::character varying, 'MARKETING'::character varying])::text[])))
);

--
-- Name: user_agreement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE user_agreement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_agreement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: user_credential; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE user_credential (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    password_hash character varying(100),
    provider character varying(20) NOT NULL,
    provider_user_id character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT user_credential_provider_check CHECK (((provider)::text = ANY ((ARRAY['LOCAL'::character varying, 'GOOGLE'::character varying, 'KAKAO'::character varying])::text[])))
);

--
-- Name: user_credential_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE user_credential ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_credential_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: user_refresh_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE user_refresh_token (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    revoked_at timestamp(6) with time zone,
    token_hash character varying(100) NOT NULL,
    user_agent character varying(300),
    user_id bigint NOT NULL
);

--
-- Name: user_refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE user_refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE users (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    deleted_at timestamp(6) with time zone,
    email character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    pet_slots integer DEFAULT 1 NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DELETED'::character varying])::text[])))
);

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: webtoon_baked_page; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE webtoon_baked_page (
    id bigint NOT NULL,
    baked_at timestamp(6) with time zone NOT NULL,
    page_no integer NOT NULL,
    run_id character varying(120) NOT NULL,
    s3_key character varying(300) NOT NULL,
    width integer NOT NULL
);

--
-- Name: webtoon_baked_page_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE webtoon_baked_page ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME webtoon_baked_page_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: webtoon_browser_link; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE webtoon_browser_link (
    id bigint NOT NULL,
    browser_uid character varying(64) NOT NULL,
    linked_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL
);

--
-- Name: webtoon_browser_link_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE webtoon_browser_link ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME webtoon_browser_link_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: webtoon_character; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE webtoon_character (
    id bigint NOT NULL,
    art_key character varying(200),
    browser_uid character varying(64),
    created_at timestamp(6) with time zone NOT NULL,
    description text,
    error character varying(300),
    name character varying(60) NOT NULL,
    owner_id bigint,
    public_id character varying(40) NOT NULL,
    source character varying(20) NOT NULL,
    status character varying(20) DEFAULT 'READY'::character varying NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT webtoon_character_source_check CHECK (((source)::text = ANY ((ARRAY['PHOTO'::character varying, 'PROMPT'::character varying, 'BUILTIN'::character varying])::text[]))),
    CONSTRAINT webtoon_character_status_check CHECK (((status)::text = ANY ((ARRAY['DRAWING'::character varying, 'READY'::character varying, 'ERROR'::character varying])::text[])))
);

--
-- Name: webtoon_character_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE webtoon_character ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME webtoon_character_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: webtoon_guest_quota; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE webtoon_guest_quota (
    id bigint NOT NULL,
    day date NOT NULL,
    ip_hash character varying(64) NOT NULL,
    used integer NOT NULL
);

--
-- Name: webtoon_guest_quota_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE webtoon_guest_quota ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME webtoon_guest_quota_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: webtoon_job; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE webtoon_job (
    id bigint NOT NULL,
    browser_uid character varying(64) NOT NULL,
    checkpoints boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    error character varying(300),
    guest_key character varying(80),
    input_json text,
    picked integer,
    public_id character varying(40) NOT NULL,
    refunded character varying(10),
    run_id character varying(64),
    stage character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    style character varying(30) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint,
    CONSTRAINT webtoon_job_refunded_check CHECK (((refunded)::text = ANY ((ARRAY['CREDIT'::character varying, 'FREE'::character varying, 'NONE'::character varying])::text[]))),
    CONSTRAINT webtoon_job_stage_check CHECK (((stage)::text = ANY ((ARRAY['STORY'::character varying, 'SHEET'::character varying, 'BOARD'::character varying, 'PAGES'::character varying])::text[]))),
    CONSTRAINT webtoon_job_status_check CHECK (((status)::text = ANY ((ARRAY['QUEUED'::character varying, 'RUNNING'::character varying, 'AWAITING_SHEET'::character varying, 'AWAITING_PICK'::character varying, 'DONE'::character varying, 'ERROR'::character varying])::text[])))
);

--
-- Name: webtoon_job_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE webtoon_job ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME webtoon_job_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: webtoon_overlay; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE webtoon_overlay (
    id bigint NOT NULL,
    data_json text NOT NULL,
    episode integer NOT NULL,
    run_id character varying(120) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

--
-- Name: webtoon_overlay_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE webtoon_overlay ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME webtoon_overlay_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: webtoon_page; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE webtoon_page (
    id bigint NOT NULL,
    bytes bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    page_no integer NOT NULL,
    run_id character varying(64) NOT NULL,
    s3_key character varying(200) NOT NULL,
    width integer NOT NULL
);

--
-- Name: webtoon_page_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE webtoon_page ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME webtoon_page_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: webtoon_page_regen; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE webtoon_page_regen (
    id character varying(32) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    error character varying(300),
    note character varying(500),
    page_no integer NOT NULL,
    run_id character varying(120) NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

--
-- Name: webtoon_story; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE webtoon_story (
    id bigint NOT NULL,
    cast_json text,
    chosen boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    genre character varying(60),
    n integer NOT NULL,
    plot text,
    run_id character varying(64) NOT NULL,
    scenes_json text,
    title character varying(200),
    user_title character varying(60)
);

--
-- Name: webtoon_story_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE webtoon_story ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME webtoon_story_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: webtoon_usage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE webtoon_usage (
    id bigint NOT NULL,
    called_at timestamp(6) with time zone NOT NULL,
    cost_basis character varying(20),
    cost_krw bigint NOT NULL,
    cost_usd double precision NOT NULL,
    error character varying(300),
    input_tokens bigint NOT NULL,
    model character varying(80) NOT NULL,
    output_tokens bigint NOT NULL,
    provider character varying(40) NOT NULL,
    run_id character varying(64) NOT NULL,
    seq integer NOT NULL,
    stage character varying(40) NOT NULL
);

--
-- Name: webtoon_usage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE webtoon_usage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME webtoon_usage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: webtoon_work; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE webtoon_work (
    id bigint NOT NULL,
    browser_uid character varying(64) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    is_public boolean DEFAULT true NOT NULL,
    job_id character varying(64) NOT NULL,
    run_id character varying(64),
    user_id bigint
);

--
-- Name: webtoon_work_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE webtoon_work ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME webtoon_work_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: zzal_anon_identity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE zzal_anon_identity (
    id bigint NOT NULL,
    anon_id character varying(40) NOT NULL,
    linked_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL
);

--
-- Name: zzal_anon_identity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE zzal_anon_identity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME zzal_anon_identity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: zzal_chat_call; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE zzal_chat_call (
    id bigint NOT NULL,
    answer character varying(40),
    answered_at timestamp(6) with time zone,
    called_at timestamp(6) with time zone NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    day_of date NOT NULL,
    expires_at timestamp(6) with time zone,
    line character varying(120) NOT NULL,
    pet_id bigint NOT NULL,
    reaction_key character varying(20),
    reply_line character varying(160),
    slot character varying(10) NOT NULL,
    CONSTRAINT zzal_chat_call_slot_check CHECK (((slot)::text = ANY ((ARRAY['BABY'::character varying, 'MORNING'::character varying, 'NOON'::character varying, 'EVENING'::character varying])::text[])))
);

--
-- Name: zzal_chat_call_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE zzal_chat_call ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME zzal_chat_call_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: zzal_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE zzal_event (
    id bigint NOT NULL,
    anon_id character varying(40) NOT NULL,
    device character varying(20),
    name character varying(60) NOT NULL,
    occurred_at timestamp(6) with time zone NOT NULL,
    path character varying(200),
    props text,
    received_at timestamp(6) with time zone NOT NULL,
    referrer character varying(200),
    source character varying(100),
    user_id bigint,
    variant character varying(30)
);

--
-- Name: zzal_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE zzal_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME zzal_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: zzal_feedback; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE zzal_feedback (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    pet_id bigint NOT NULL,
    rating integer NOT NULL,
    tags character varying(200),
    text text,
    user_id bigint NOT NULL
);

--
-- Name: zzal_feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE zzal_feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME zzal_feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: zzal_game; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE zzal_game (
    id bigint NOT NULL,
    answers character varying(10) NOT NULL,
    finished_at timestamp(6) with time zone,
    hits integer NOT NULL,
    pet_id bigint NOT NULL,
    picks character varying(10) NOT NULL,
    started_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    kind character varying(12),
    survived_ms bigint,
    CONSTRAINT zzal_game_kind_check CHECK (((kind)::text = ANY ((ARRAY['LEFT_RIGHT'::character varying, 'RUN'::character varying])::text[])))
);

--
-- Name: zzal_game_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE zzal_game ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME zzal_game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: zzal_gen_job; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE zzal_gen_job (
    id bigint NOT NULL,
    attempt integer NOT NULL,
    error_code character varying(30),
    finished_at timestamp(6) with time zone,
    kind character varying(20) NOT NULL,
    motion_id bigint,
    pet_id bigint NOT NULL,
    pipeline_version character varying(20) NOT NULL,
    running_at timestamp(6) with time zone,
    started_at timestamp(6) with time zone NOT NULL,
    status character varying(20) NOT NULL,
    total_cost_usd numeric(10,4),
    CONSTRAINT zzal_gen_job_error_code_check CHECK (((error_code)::text = ANY ((ARRAY['TIMEOUT'::character varying, 'MODERATION_BLOCKED'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT zzal_gen_job_kind_check CHECK (((kind)::text = ANY ((ARRAY['HATCH'::character varying, 'MOTION'::character varying])::text[]))),
    CONSTRAINT zzal_gen_job_status_check CHECK (((status)::text = ANY ((ARRAY['QUEUED'::character varying, 'RUNNING'::character varying, 'SUCCEEDED'::character varying, 'FAILED'::character varying])::text[])))
);

--
-- Name: zzal_gen_job_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE zzal_gen_job ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME zzal_gen_job_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: zzal_gen_step; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE zzal_gen_step (
    id bigint NOT NULL,
    cost_usd numeric(10,4),
    error_code character varying(30),
    finished_at timestamp(6) with time zone,
    job_id bigint NOT NULL,
    model character varying(60),
    name character varying(40) NOT NULL,
    output_key character varying(300),
    output_text text,
    seq integer NOT NULL,
    started_at timestamp(6) with time zone NOT NULL,
    status character varying(20) NOT NULL,
    CONSTRAINT zzal_gen_step_error_code_check CHECK (((error_code)::text = ANY ((ARRAY['TIMEOUT'::character varying, 'MODERATION_BLOCKED'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT zzal_gen_step_status_check CHECK (((status)::text = ANY ((ARRAY['QUEUED'::character varying, 'RUNNING'::character varying, 'SUCCEEDED'::character varying, 'FAILED'::character varying])::text[])))
);

--
-- Name: zzal_gen_step_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE zzal_gen_step ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME zzal_gen_step_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: zzal_motion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE zzal_motion (
    id bigint NOT NULL,
    attempts integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    gate_note character varying(300),
    gate_verdict character varying(20),
    gate_version character varying(20),
    human_note character varying(500),
    human_verdict character varying(20),
    image_key character varying(300),
    name character varying(60) NOT NULL,
    opened_at timestamp(6) with time zone,
    pet_id bigint NOT NULL,
    pipeline_version character varying(20),
    reviewed_at timestamp(6) with time zone,
    seq integer NOT NULL,
    source character varying(20),
    status character varying(20) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    claimed_at timestamp(6) with time zone,
    claimed_by character varying(60),
    layer character varying(10),
    night_of date,
    regen_round integer DEFAULT 0 NOT NULL,
    revealed_at timestamp(6) with time zone,
    seen_at timestamp(6) with time zone,
    unlocked_at timestamp(6) with time zone
);

--
-- Name: zzal_motion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE zzal_motion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME zzal_motion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: zzal_night_run; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE zzal_night_run (
    night_of date NOT NULL,
    carried integer DEFAULT 0 NOT NULL,
    claimed integer DEFAULT 0 NOT NULL,
    finished_at timestamp(6) with time zone,
    queued integer DEFAULT 0 NOT NULL,
    server character varying(60),
    started_at timestamp(6) with time zone NOT NULL
);

--
-- Name: zzal_pet; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE zzal_pet (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    death_reason character varying(20),
    food integer NOT NULL,
    food_at timestamp(6) with time zone,
    fullness integer NOT NULL,
    fullness_at timestamp(6) with time zone,
    happiness integer NOT NULL,
    happiness_at timestamp(6) with time zone,
    hatch_started_at timestamp(6) with time zone NOT NULL,
    hatched_at timestamp(6) with time zone,
    identity_text text,
    last_cared_at timestamp(6) with time zone,
    name character varying(20) NOT NULL,
    note character varying(200),
    phase character varying(16) NOT NULL,
    sheet_image_key character varying(300),
    sleep_started_at timestamp(6) with time zone,
    source_image_key character varying(300) NOT NULL,
    trash integer NOT NULL,
    trash_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    tutorial_done_at timestamp(6) with time zone,
    background character varying(32),
    bath_count integer DEFAULT 0 NOT NULL,
    care_miss integer DEFAULT 0 NOT NULL,
    chat_answers integer DEFAULT 0 NOT NULL,
    clean_miss_armed boolean DEFAULT false NOT NULL,
    clean_zero_sec bigint DEFAULT 0 NOT NULL,
    cleans integer DEFAULT 0 NOT NULL,
    days_together integer DEFAULT 0 NOT NULL,
    dev_clock_offset_seconds bigint DEFAULT 0 NOT NULL,
    feeds integer DEFAULT 0 NOT NULL,
    fullness_awake_sec bigint DEFAULT 0 NOT NULL,
    fullness_miss_armed boolean DEFAULT false NOT NULL,
    fullness_zero_sec bigint DEFAULT 0 NOT NULL,
    game_starts integer DEFAULT 0 NOT NULL,
    happiness_awake_sec bigint DEFAULT 0 NOT NULL,
    happiness_miss_armed boolean DEFAULT false NOT NULL,
    happiness_zero_sec bigint DEFAULT 0 NOT NULL,
    hatch_pipeline_version character varying(20),
    intimacy integer DEFAULT 0 NOT NULL,
    intimacy_peak integer DEFAULT 0 NOT NULL,
    last_seen_at timestamp(6) with time zone,
    last_visit_date date,
    left_right_wins integer DEFAULT 0 NOT NULL,
    nap_count integer DEFAULT 0 NOT NULL,
    overslept boolean DEFAULT false NOT NULL,
    personality character varying(10),
    settled_at timestamp(6) with time zone,
    shares integer DEFAULT 0 NOT NULL,
    sleep_kind character varying(10),
    sleep_wake_count integer DEFAULT 0 NOT NULL,
    slept_at timestamp(6) with time zone,
    snack_streak integer DEFAULT 0 NOT NULL,
    today_bath_done boolean DEFAULT false NOT NULL,
    today_care_intimacy integer DEFAULT 0 NOT NULL,
    today_care_miss integer DEFAULT 0 NOT NULL,
    today_games integer DEFAULT 0 NOT NULL,
    today_pet_count integer DEFAULT 0 NOT NULL,
    trash_awake_sec bigint DEFAULT 0 NOT NULL,
    woke_at timestamp(6) with time zone,
    world character varying(40),
    zero_miss_days integer DEFAULT 0 NOT NULL,
    pets integer DEFAULT 0 NOT NULL,
    last_night_care_miss integer DEFAULT 0 NOT NULL,
    last_night_of date,
    healed_at timestamp(6) with time zone,
    natural_sick_due_awake_sec bigint,
    natural_sick_rolls integer DEFAULT 0 NOT NULL,
    sick_awake_sec bigint DEFAULT 0 NOT NULL,
    sick_kind character varying(20),
    sick_since timestamp(6) with time zone,
    absence_awake_sec bigint DEFAULT 0 NOT NULL,
    night_scene_at timestamp(6) with time zone,
    scenes_enabled_at timestamp(6) with time zone,
    trip_started_at timestamp(6) with time zone,
    pending_night_scene_at timestamp(6) with time zone,
    bonus_piece boolean DEFAULT false NOT NULL,
    good_day_pending boolean DEFAULT false NOT NULL,
    good_day_today boolean DEFAULT false NOT NULL,
    last_night_piece_streak integer DEFAULT 0 NOT NULL,
    layer_two_done_at timestamp(6) with time zone,
    piece_streak integer DEFAULT 0 NOT NULL,
    pieces_enabled_at timestamp(6) with time zone,
    today_chat_answers integer DEFAULT 0 NOT NULL,
    today_cleans integer DEFAULT 0 NOT NULL,
    today_feeds integer DEFAULT 0 NOT NULL,
    today_game_wins integer DEFAULT 0 NOT NULL,
    today_snacks integer DEFAULT 0 NOT NULL,
    last_postcard_date date,
    leave_enabled boolean DEFAULT true NOT NULL,
    leave_notice_at timestamp(6) with time zone,
    pending_night_mood character varying(20),
    pending_night_sick boolean DEFAULT false NOT NULL,
    postcard_count integer DEFAULT 0 NOT NULL,
    CONSTRAINT zzal_pet_personality_check CHECK (((personality)::text = ANY ((ARRAY['GENTLE'::character varying, 'LIVELY'::character varying, 'SHY'::character varying, 'CLINGY'::character varying, 'COOL'::character varying])::text[]))),
    CONSTRAINT zzal_pet_phase_check CHECK (((phase)::text = ANY ((ARRAY['DRAFT'::character varying, 'HATCHING'::character varying, 'ALIVE'::character varying, 'FAILED'::character varying, 'DEAD'::character varying])::text[]))),
    CONSTRAINT zzal_pet_sick_kind_check CHECK (((sick_kind)::text = ANY ((ARRAY['NEGLECT'::character varying, 'DIRTY'::character varying, 'UPSET'::character varying, 'NATURAL'::character varying])::text[]))),
    CONSTRAINT zzal_pet_sleep_kind_check CHECK (((sleep_kind)::text = ANY ((ARRAY['NIGHT'::character varying, 'NAP'::character varying])::text[])))
);

--
-- Name: zzal_pet_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE zzal_pet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME zzal_pet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: zzal_pets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE zzal_pets (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    deleted_at timestamp(6) with time zone,
    extra_text character varying(200),
    genre_pick character varying(20),
    genre_text character varying(100),
    name character varying(12) NOT NULL,
    personality_pick character varying(20),
    personality_text character varying(100),
    pipeline_version character varying(20),
    speech_pick character varying(20),
    speech_text character varying(100),
    status character varying(20) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    upload_id bigint NOT NULL,
    user_id bigint NOT NULL,
    world_pick character varying(20),
    world_text character varying(100),
    CONSTRAINT zzal_pets_status_check CHECK (((status)::text = ANY ((ARRAY['HATCHING'::character varying, 'ALIVE'::character varying, 'FAILED'::character varying, 'TRAVELING'::character varying, 'DELETED'::character varying])::text[])))
);

--
-- Name: zzal_pets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE zzal_pets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME zzal_pets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: zzal_postcard; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE zzal_postcard (
    id bigint NOT NULL,
    delivered_at timestamp(6) with time zone,
    pet_id bigint NOT NULL,
    place character varying(40) NOT NULL,
    seq integer NOT NULL,
    written_at timestamp(6) with time zone NOT NULL
);

--
-- Name: zzal_postcard_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE zzal_postcard ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME zzal_postcard_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: zzal_scene; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE zzal_scene (
    id bigint NOT NULL,
    background character varying(40) NOT NULL,
    mood character varying(20) NOT NULL,
    motion_key character varying(40) NOT NULL,
    night boolean DEFAULT false NOT NULL,
    pet_id bigint NOT NULL,
    prop character varying(40),
    scene_at timestamp(6) with time zone NOT NULL
);

--
-- Name: zzal_scene_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE zzal_scene ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME zzal_scene_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comic_character_sheet comic_character_sheet_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY comic_character_sheet
    ADD CONSTRAINT comic_character_sheet_pkey PRIMARY KEY (id);

--
-- Name: comic_feedback comic_feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY comic_feedback
    ADD CONSTRAINT comic_feedback_pkey PRIMARY KEY (id);

--
-- Name: comic_gif_job comic_gif_job_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY comic_gif_job
    ADD CONSTRAINT comic_gif_job_pkey PRIMARY KEY (id);

--
-- Name: comic_gif_take comic_gif_take_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY comic_gif_take
    ADD CONSTRAINT comic_gif_take_pkey PRIMARY KEY (id);

--
-- Name: comic_usage comic_usage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY comic_usage
    ADD CONSTRAINT comic_usage_pkey PRIMARY KEY (id);

--
-- Name: comics comics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY comics
    ADD CONSTRAINT comics_pkey PRIMARY KEY (id);

--
-- Name: credit_event credit_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY credit_event
    ADD CONSTRAINT credit_event_pkey PRIMARY KEY (id);

--
-- Name: webtoon_character uk8me8ofbcx59c17iy3r8icx760; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_character
    ADD CONSTRAINT uk8me8ofbcx59c17iy3r8icx760 UNIQUE (public_id);

--
-- Name: user_agreement uk_agreement_user_type_version; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_agreement
    ADD CONSTRAINT uk_agreement_user_type_version UNIQUE (user_id, type, version);

--
-- Name: zzal_anon_identity uk_anon_identity; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY zzal_anon_identity
    ADD CONSTRAINT uk_anon_identity UNIQUE (anon_id, user_id);

--
-- Name: user_credential uk_credential_provider_uid; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_credential
    ADD CONSTRAINT uk_credential_provider_uid UNIQUE (provider, provider_user_id);

--
-- Name: user_credential uk_credential_user_provider; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_credential
    ADD CONSTRAINT uk_credential_user_provider UNIQUE (user_id, provider);

--
-- Name: credit_event uk_credit_event_once; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY credit_event
    ADD CONSTRAINT uk_credit_event_once UNIQUE (user_id, reason, domain, ref_id);

--
-- Name: zzal_feedback uk_feedback_user_pet; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY zzal_feedback
    ADD CONSTRAINT uk_feedback_user_pet UNIQUE (user_id, pet_id);

--
-- Name: zzal_gen_step uk_gen_step_job_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY zzal_gen_step
    ADD CONSTRAINT uk_gen_step_job_name UNIQUE (job_id, name);

--
-- Name: user_refresh_token uk_refresh_token_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_refresh_token
    ADD CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash);

--
-- Name: upload_ticket uk_upload_ticket_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY upload_ticket
    ADD CONSTRAINT uk_upload_ticket_key UNIQUE (s3_key);

--
-- Name: comic_usage uk_usage_owner_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY comic_usage
    ADD CONSTRAINT uk_usage_owner_date UNIQUE (owner_key, usage_date);

--
-- Name: users uk_users_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY users
    ADD CONSTRAINT uk_users_email UNIQUE (email);

--
-- Name: webtoon_baked_page uk_webtoon_baked_page; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_baked_page
    ADD CONSTRAINT uk_webtoon_baked_page UNIQUE (run_id, page_no, width);

--
-- Name: webtoon_browser_link uk_webtoon_browser_link; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_browser_link
    ADD CONSTRAINT uk_webtoon_browser_link UNIQUE (user_id, browser_uid);

--
-- Name: webtoon_guest_quota uk_webtoon_guest_quota_day; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_guest_quota
    ADD CONSTRAINT uk_webtoon_guest_quota_day UNIQUE (ip_hash, day);

--
-- Name: webtoon_overlay uk_webtoon_overlay; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_overlay
    ADD CONSTRAINT uk_webtoon_overlay UNIQUE (run_id, episode);

--
-- Name: webtoon_page uk_webtoon_page_one; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_page
    ADD CONSTRAINT uk_webtoon_page_one UNIQUE (run_id, page_no, width);

--
-- Name: webtoon_story uk_webtoon_story_one; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_story
    ADD CONSTRAINT uk_webtoon_story_one UNIQUE (run_id, n);

--
-- Name: webtoon_usage uk_webtoon_usage_call; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_usage
    ADD CONSTRAINT uk_webtoon_usage_call UNIQUE (run_id, seq);

--
-- Name: zzal_chat_call uk_zzal_chat_call_day_slot; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY zzal_chat_call
    ADD CONSTRAINT uk_zzal_chat_call_day_slot UNIQUE (pet_id, day_of, slot);

--
-- Name: zzal_motion uk_zzal_motion_pet_seq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY zzal_motion
    ADD CONSTRAINT uk_zzal_motion_pet_seq UNIQUE (pet_id, seq);

--
-- Name: comic_feedback_chip ukcb1qwv6v6v945vude13fyaqlc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY comic_feedback_chip
    ADD CONSTRAINT ukcb1qwv6v6v945vude13fyaqlc UNIQUE (feedback_id, chip);

--
-- Name: webtoon_job uki7ma3ody3nx4q81yeos64cisp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_job
    ADD CONSTRAINT uki7ma3ody3nx4q81yeos64cisp UNIQUE (public_id);

--
-- Name: webtoon_work ukoi26mq60h23j2h9buy70rqlg1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_work
    ADD CONSTRAINT ukoi26mq60h23j2h9buy70rqlg1 UNIQUE (job_id);

--
-- Name: upload_ticket upload_ticket_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY upload_ticket
    ADD CONSTRAINT upload_ticket_pkey PRIMARY KEY (id);

--
-- Name: user_agreement user_agreement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_agreement
    ADD CONSTRAINT user_agreement_pkey PRIMARY KEY (id);

--
-- Name: user_credential user_credential_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_credential
    ADD CONSTRAINT user_credential_pkey PRIMARY KEY (id);

--
-- Name: user_refresh_token user_refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_refresh_token
    ADD CONSTRAINT user_refresh_token_pkey PRIMARY KEY (id);

--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

--
-- Name: webtoon_baked_page webtoon_baked_page_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_baked_page
    ADD CONSTRAINT webtoon_baked_page_pkey PRIMARY KEY (id);

--
-- Name: webtoon_browser_link webtoon_browser_link_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_browser_link
    ADD CONSTRAINT webtoon_browser_link_pkey PRIMARY KEY (id);

--
-- Name: webtoon_character webtoon_character_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_character
    ADD CONSTRAINT webtoon_character_pkey PRIMARY KEY (id);

--
-- Name: webtoon_guest_quota webtoon_guest_quota_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_guest_quota
    ADD CONSTRAINT webtoon_guest_quota_pkey PRIMARY KEY (id);

--
-- Name: webtoon_job webtoon_job_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_job
    ADD CONSTRAINT webtoon_job_pkey PRIMARY KEY (id);

--
-- Name: webtoon_overlay webtoon_overlay_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_overlay
    ADD CONSTRAINT webtoon_overlay_pkey PRIMARY KEY (id);

--
-- Name: webtoon_page webtoon_page_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_page
    ADD CONSTRAINT webtoon_page_pkey PRIMARY KEY (id);

--
-- Name: webtoon_page_regen webtoon_page_regen_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_page_regen
    ADD CONSTRAINT webtoon_page_regen_pkey PRIMARY KEY (id);

--
-- Name: webtoon_story webtoon_story_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_story
    ADD CONSTRAINT webtoon_story_pkey PRIMARY KEY (id);

--
-- Name: webtoon_usage webtoon_usage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_usage
    ADD CONSTRAINT webtoon_usage_pkey PRIMARY KEY (id);

--
-- Name: webtoon_work webtoon_work_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY webtoon_work
    ADD CONSTRAINT webtoon_work_pkey PRIMARY KEY (id);

--
-- Name: zzal_anon_identity zzal_anon_identity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY zzal_anon_identity
    ADD CONSTRAINT zzal_anon_identity_pkey PRIMARY KEY (id);

--
-- Name: zzal_chat_call zzal_chat_call_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY zzal_chat_call
    ADD CONSTRAINT zzal_chat_call_pkey PRIMARY KEY (id);

--
-- Name: zzal_event zzal_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY zzal_event
    ADD CONSTRAINT zzal_event_pkey PRIMARY KEY (id);

--
-- Name: zzal_feedback zzal_feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY zzal_feedback
    ADD CONSTRAINT zzal_feedback_pkey PRIMARY KEY (id);

--
-- Name: zzal_game zzal_game_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY zzal_game
    ADD CONSTRAINT zzal_game_pkey PRIMARY KEY (id);

--
-- Name: zzal_gen_job zzal_gen_job_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY zzal_gen_job
    ADD CONSTRAINT zzal_gen_job_pkey PRIMARY KEY (id);

--
-- Name: zzal_gen_step zzal_gen_step_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY zzal_gen_step
    ADD CONSTRAINT zzal_gen_step_pkey PRIMARY KEY (id);

--
-- Name: zzal_motion zzal_motion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY zzal_motion
    ADD CONSTRAINT zzal_motion_pkey PRIMARY KEY (id);

--
-- Name: zzal_night_run zzal_night_run_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY zzal_night_run
    ADD CONSTRAINT zzal_night_run_pkey PRIMARY KEY (night_of);

--
-- Name: zzal_pet zzal_pet_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY zzal_pet
    ADD CONSTRAINT zzal_pet_pkey PRIMARY KEY (id);

--
-- Name: zzal_pets zzal_pets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY zzal_pets
    ADD CONSTRAINT zzal_pets_pkey PRIMARY KEY (id);

--
-- Name: zzal_postcard zzal_postcard_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY zzal_postcard
    ADD CONSTRAINT zzal_postcard_pkey PRIMARY KEY (id);

--
-- Name: zzal_scene zzal_scene_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY zzal_scene
    ADD CONSTRAINT zzal_scene_pkey PRIMARY KEY (id);

--
-- Name: idx_anon_identity_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_anon_identity_user ON zzal_anon_identity USING btree (user_id);

--
-- Name: idx_credit_event_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_credit_event_user ON credit_event USING btree (user_id, id);

--
-- Name: idx_event_anon; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_anon ON zzal_event USING btree (anon_id);

--
-- Name: idx_event_name_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_name_time ON zzal_event USING btree (name, occurred_at);

--
-- Name: idx_event_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_user ON zzal_event USING btree (user_id);

--
-- Name: idx_feedback_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_feedback_created ON zzal_feedback USING btree (created_at);

--
-- Name: idx_feedback_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_feedback_owner ON comic_feedback USING btree (owner_key);

--
-- Name: idx_game_pet; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_game_pet ON zzal_game USING btree (pet_id);

--
-- Name: idx_game_user_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_game_user_time ON zzal_game USING btree (user_id, started_at);

--
-- Name: idx_gen_job_pet; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_gen_job_pet ON zzal_gen_job USING btree (pet_id);

--
-- Name: idx_gen_job_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_gen_job_status ON zzal_gen_job USING btree (status);

--
-- Name: idx_gen_step_job; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_gen_step_job ON zzal_gen_step USING btree (job_id);

--
-- Name: idx_job_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_job_owner ON comic_gif_job USING btree (owner_key);

--
-- Name: idx_job_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_job_status ON comic_gif_job USING btree (status);

--
-- Name: idx_refresh_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_user ON user_refresh_token USING btree (user_id);

--
-- Name: idx_sheet_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sheet_owner ON comic_character_sheet USING btree (owner_key);

--
-- Name: idx_sheet_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sheet_status ON comic_character_sheet USING btree (status);

--
-- Name: idx_take_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_take_status ON comic_gif_take USING btree (status);

--
-- Name: idx_upload_ticket_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_upload_ticket_user ON upload_ticket USING btree (user_id);

--
-- Name: idx_webtoon_baked_page_run; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_webtoon_baked_page_run ON webtoon_baked_page USING btree (run_id);

--
-- Name: idx_webtoon_browser_link_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_webtoon_browser_link_user ON webtoon_browser_link USING btree (user_id);

--
-- Name: idx_webtoon_character_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_webtoon_character_owner ON webtoon_character USING btree (owner_id, id);

--
-- Name: idx_webtoon_character_public_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_webtoon_character_public_id ON webtoon_character USING btree (public_id);

--
-- Name: idx_webtoon_job_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_webtoon_job_status ON webtoon_job USING btree (status, id);

--
-- Name: idx_webtoon_job_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_webtoon_job_user ON webtoon_job USING btree (user_id);

--
-- Name: idx_webtoon_page_run; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_webtoon_page_run ON webtoon_page USING btree (run_id);

--
-- Name: idx_webtoon_story_run; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_webtoon_story_run ON webtoon_story USING btree (run_id);

--
-- Name: idx_webtoon_usage_called_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_webtoon_usage_called_at ON webtoon_usage USING btree (called_at);

--
-- Name: idx_webtoon_usage_run; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_webtoon_usage_run ON webtoon_usage USING btree (run_id);

--
-- Name: idx_webtoon_work_uid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_webtoon_work_uid ON webtoon_work USING btree (browser_uid);

--
-- Name: idx_webtoon_work_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_webtoon_work_user ON webtoon_work USING btree (user_id);

--
-- Name: idx_zzal_chat_call_pet; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_zzal_chat_call_pet ON zzal_chat_call USING btree (pet_id);

--
-- Name: idx_zzal_motion_pet; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_zzal_motion_pet ON zzal_motion USING btree (pet_id);

--
-- Name: idx_zzal_motion_review; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_zzal_motion_review ON zzal_motion USING btree (human_verdict);

--
-- Name: idx_zzal_pet_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_zzal_pet_user ON zzal_pet USING btree (user_id);

--
-- Name: idx_zzal_postcard_pet; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_zzal_postcard_pet ON zzal_postcard USING btree (pet_id);

--
-- Name: idx_zzal_scene_pet; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_zzal_scene_pet ON zzal_scene USING btree (pet_id);

--
-- Name: ix_pets_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_pets_user ON zzal_pets USING btree (user_id, status);

--
-- Name: user_agreement fk_agreement_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_agreement
    ADD CONSTRAINT fk_agreement_user FOREIGN KEY (user_id) REFERENCES users(id);

--
-- Name: user_credential fk_credential_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_credential
    ADD CONSTRAINT fk_credential_user FOREIGN KEY (user_id) REFERENCES users(id);

--
-- Name: user_refresh_token fk_refresh_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_refresh_token
    ADD CONSTRAINT fk_refresh_user FOREIGN KEY (user_id) REFERENCES users(id);

--
-- Name: comic_gif_job fkbw6c8liuvln0j9ujcf06e3i5f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY comic_gif_job
    ADD CONSTRAINT fkbw6c8liuvln0j9ujcf06e3i5f FOREIGN KEY (sheet_id) REFERENCES comic_character_sheet(id);

--
-- Name: comic_gif_take fkl8ug91ckkj7iu8s9b1i3wpdui; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY comic_gif_take
    ADD CONSTRAINT fkl8ug91ckkj7iu8s9b1i3wpdui FOREIGN KEY (job_id) REFERENCES comic_gif_job(id);

--
-- Name: comic_feedback_chip fkppc5t6j5k41hujg3ekshofyde; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY comic_feedback_chip
    ADD CONSTRAINT fkppc5t6j5k41hujg3ekshofyde FOREIGN KEY (feedback_id) REFERENCES comic_feedback(id);

--
-- Name: comic_feedback fks4x2rt3j5v6cuiamjud7gyepc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY comic_feedback
    ADD CONSTRAINT fks4x2rt3j5v6cuiamjud7gyepc FOREIGN KEY (job_id) REFERENCES comic_gif_job(id);

--
--
