-- 채팅 대화형 구조(#704) — 부름 1행 = 부름+답 1회였던 것을 "세션 1행 + 턴 N행" 으로.
--
-- ★ 추가만 한다. zzal_chat_call 은 그대로 두고 읽기만 한다(옛 행은 세션 1턴처럼 보인다 — ChatService 의 어댑터).
--   새 부름·답은 이 두 표에 쓴다.
-- ★ (펫, 날, 슬롯) 유니크는 옛 표와 같은 규칙 — 같은 부름이 두 번 생기지 않는다.

CREATE TABLE zzal_chat_session (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id bigint NOT NULL,
    day_of date NOT NULL,
    slot character varying(10) NOT NULL,
    kind character varying(16) NOT NULL,
    started_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone,
    closed_at timestamp(6) with time zone,
    close_reason character varying(10),
    round_count integer NOT NULL DEFAULT 0,
    last_user_line character varying(40),
    reward_given boolean NOT NULL DEFAULT false,
    generator character varying(10),
    cost_usd numeric(10,6),
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_zzal_chat_session_day_slot UNIQUE (pet_id, day_of, slot),
    CONSTRAINT zzal_chat_session_slot_check CHECK (((slot)::text = ANY ((ARRAY['BABY'::character varying, 'MORNING'::character varying, 'NOON'::character varying, 'EVENING'::character varying])::text[]))),
    CONSTRAINT zzal_chat_session_kind_check CHECK (((kind)::text = ANY ((ARRAY['BABY'::character varying, 'FIRST_MEET'::character varying, 'DAILY'::character varying, 'LONG_ABSENCE'::character varying])::text[]))),
    CONSTRAINT zzal_chat_session_close_reason_check CHECK (((close_reason)::text = ANY ((ARRAY['CLOSED'::character varying, 'EXPIRED'::character varying, 'ABANDONED'::character varying])::text[])))
);
CREATE INDEX idx_zzal_chat_session_pet ON zzal_chat_session (pet_id);

CREATE TABLE zzal_chat_turn (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint NOT NULL,
    pet_id bigint NOT NULL,
    idx integer NOT NULL,
    speaker character varying(4) NOT NULL,
    turn_type character varying(12),
    line character varying(160) NOT NULL,
    motion character varying(20),
    generator character varying(10),
    filtered_reason character varying(32),
    question_item character varying(10),
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_zzal_chat_turn_session_idx UNIQUE (session_id, idx),
    CONSTRAINT zzal_chat_turn_speaker_check CHECK (((speaker)::text = ANY ((ARRAY['PET'::character varying, 'USER'::character varying])::text[]))),
    CONSTRAINT zzal_chat_turn_type_check CHECK (((turn_type)::text = ANY ((ARRAY['FIRST_MEET'::character varying, 'GREETING'::character varying, 'REUNION'::character varying, 'CONTINUE'::character varying, 'CLOSE'::character varying])::text[]))),
    CONSTRAINT zzal_chat_turn_question_item_check CHECK (((question_item)::text = ANY ((ARRAY['CALL_ME'::character varying, 'WHO'::character varying, 'FUN'::character varying, 'LIKES'::character varying, 'MOOD'::character varying])::text[])))
);
CREATE INDEX idx_zzal_chat_turn_pet ON zzal_chat_turn (pet_id);

-- 아이가 사용자를 부르는 말. 대화 중 호칭 질문의 답에서 코드가 뽑아 둔다(프로필 callMe 보다 우선).
ALTER TABLE zzal_pet ADD COLUMN IF NOT EXISTS call_me character varying(20);
