-- 동작 요청 — 사용자가 "이런 동작도 보고 싶어요" 를 자유 글로 남기는 표.
--
-- ★★ 왜 표를 따로 두나 — 행동 기록(zzal_event)에는 이 글을 담을 수 없다.
--   AnalyticsService 는 허용 키 밖의 값을 통째로 버리고, 사람이 쓴 글은 <b>일부러</b> 허용 목록에
--   넣지 않았다(이메일·후기 본문·캐릭터 설명이 그 목록 밖에 있는 것과 같은 이유다).
--   그래서 글은 여기에만 남고, 기록 쪽에는 "남겼다" 는 사실만 고정된 이름으로 한 줄 간다.
--
-- ★ 한 번 부를 때마다 한 줄이다(후기처럼 유니크를 걸지 않는다). 보고 싶은 동작은 여러 개일 수
--   있고, 한 사람이 쌓아 가는 목록 자체가 우리가 알고 싶은 것이다. 대신 무한히 쌓이지 않도록
--   하루 상한을 서비스 쪽에서 센다 — 그 셈이 이 표의 (pet_id, created_at) 색인을 쓴다.
--
-- ★ 글 길이를 60자로 <b>DB 에서도</b> 막는다. 요청 검증(@Size)만 두면 다른 경로로 들어오는 날
--   길이가 안 맞아도 아무 소리가 안 난다. 화면에 보이는 글자 수 표시와 같은 값이다.

CREATE TABLE zzal_motion_wish (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 어느 아이에게 바라는 동작인가. 소유권은 요청을 받는 자리에서 이미 판정한다.
    pet_id bigint NOT NULL,
    -- 누가 남겼나. 펫으로도 주인을 알 수 있지만, 펫이 떠난 뒤에도 "누가 무엇을 바랐나" 가 남아야 한다.
    user_id bigint NOT NULL,
    -- 사람이 쓴 글. ★ 이 칸의 내용은 행동 기록으로 흘려보내지 않는다.
    text character varying(60) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL
);

-- 하루 상한을 세는 조회가 그대로 타는 색인 — (pet_id, created_at).
CREATE INDEX idx_zzal_motion_wish_pet_created ON zzal_motion_wish (pet_id, created_at);
