-- 튜토리얼·시계 컬럼과 새 표 두 개.
--
-- ★ 왜 따로 필요했나 — V1(기준선)은 이미 표가 있는 DB 에서 건너뛰도록 만들었다(baseline-version 1).
--   그래서 기준선 안에만 넣어 둔 새 컬럼·새 표는 기존 DB 에 만들어지지 않는다.
--   로컬은 예전 ddl-auto: update 가 이미 만들어 둬서 이 사실이 안 드러났고,
--   테스트 서버에서 validate 가 "missing column [clock_started_at]" 으로 기동을 막았다.
--
-- ★ 여기서 배운 규칙 — 엔티티에 칸이나 표를 더하면 기준선이 아니라 새 번호 파일에 쓴다.
--   기준선은 빈 DB 를 세우는 용도뿐이다.
--
-- ★ IF NOT EXISTS 를 쓰지 않는다 — 있으면 "이미 있네" 하고 넘어가는데, 그 표가 이름만 같고
--   안이 다를 수 있다. CREATE TABLE IF NOT EXISTS 는 표가 있으면 괄호 안의 제약을 하나도
--   적용하지 않는다. 예상 밖의 스키마는 조용히 지나가는 것보다 여기서 죽는 편이 낫다.

-- 시계가 켜진 순간. null 이면 아직 튜토리얼 중이라 게이지·병·자동 취침이 모두 멈춰 있다.
ALTER TABLE zzal_pet ADD COLUMN clock_started_at timestamp(6) with time zone;

-- 튜토리얼에서 끝낸 칸 수(0~9). 화면이 아니라 서버가 갖는다.
ALTER TABLE zzal_pet ADD COLUMN tutorial_step integer DEFAULT 0 NOT NULL;

-- 공유 링크. (pet_id, motion_key) 한 쌍에 링크 하나 — 같은 동작을 다시 공유해도 주소가 안 바뀐다.
CREATE TABLE zzal_shares (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    motion_key character varying(40) NOT NULL,
    pet_id bigint NOT NULL,
    token character varying(32) NOT NULL,
    views bigint DEFAULT 0 NOT NULL,
    CONSTRAINT uk_zzal_shares_token UNIQUE (token),
    CONSTRAINT uk_zzal_shares_pet_motion UNIQUE (pet_id, motion_key)
);

-- 부화를 기다리는 동안 받는 6문항. 중간에 이탈하는 사람이 있으므로 전부 nullable 이다.
CREATE TABLE zzal_user_profiles (
    user_id bigint PRIMARY KEY,
    age_band character varying(20),
    call_me character varying(20),
    came_from character varying(40),
    draws character varying(20),
    relation character varying(20),
    visit_time character varying(20),
    updated_at timestamp(6) with time zone NOT NULL
);
