-- 굽기 일감과 나온 판 (2차 명세 1·5장)
--
-- ★ 이 단계에서는 <b>모양만</b> 만든다. 여기에 줄을 넣고 옮기는 것(굽기 시작·게이트·관리자 API)은 다음 단계다.


-- ── 2) 굽기 일감 ─────────────────────────────────────────────────────────
--
-- ★ "몇 월 며칠 밤" 같은 칸이 없다 — 날짜 단위 이월을 버렸기 때문이다(정본 1.8).
--   줄은 판정이 끝날 때까지 그대로 있고, 판정된 것만 나간다.

CREATE TABLE zzal_bake (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id bigint NOT NULL,
    motion_key character varying(40) NOT NULL,
    -- NEW(구르기) · FIRST(뒤로 넘어짐) · LAYER3 — 판정 화면에서 셋을 따로 본다
    bake_group character varying(20) NOT NULL,
    -- BAKING · REBAKING · JUDGING · PUBLISH_WAIT · PUBLISHED · HOLD
    status character varying(20) NOT NULL,
    -- 0 = 서버 API 1판, 1~2 = 맥미니 CLI 3판씩
    round integer DEFAULT 0 NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE INDEX idx_zzal_bake_pet ON zzal_bake (pet_id);
CREATE INDEX idx_zzal_bake_status ON zzal_bake (status);


-- ── 3) 나온 판 ───────────────────────────────────────────────────────────
--
-- ★ 한 일감에 최대 일곱 판이 달린다(서버 1 + 맥미니 3 × 2라운드). 판정할 때 전부 보여 주고 고른다.
-- ★ 게이트 판정을 지우지 않고 남기는 이유 — 사람이 고른 것과 대조해야 게이트를 보정할 수 있다.

CREATE TABLE zzal_bake_candidate (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bake_id bigint NOT NULL,
    round integer DEFAULT 0 NOT NULL,
    grid_key character varying(300) NOT NULL,
    webp_key character varying(300) NOT NULL,
    gate_score double precision,
    -- SUCCESS · NEEDS_REVIEW · FAIL
    gate_verdict character varying(20) NOT NULL,
    chosen boolean DEFAULT false NOT NULL,
    created_at timestamp(6) with time zone NOT NULL
);

CREATE INDEX idx_zzal_bake_candidate_bake ON zzal_bake_candidate (bake_id);


